//! `slideforge-math` — math rendering engine for slideforge.
//!
//! This crate implements the [`MathRenderer`] plugin surface from
//! `slideforge-plugin-api`. It is the built-in LaTeX → OMML/MathML renderer
//! shipped with slideforge.
//!
//! ## Pipeline
//!
//! ```text
//! MathNode (raw LaTeX + span)
//!   └─► substitute()  — @{var} interpolation
//!         └─► parse()    — LaTeX → MathAst
//!               └─► omml::render() / (future: mathml::render())
//!                     └─► Vec<u8>  — OMML or MathML bytes
//! ```
//!
//! ## Supported outputs
//!
//! | Format | Status |
//! |--------|--------|
//! | [`MathOutputFormat::Omml`] | Planned (story STORY-029) |
//! | [`MathOutputFormat::MathMl`] | Not yet implemented |
//! | [`MathOutputFormat::Pdf`] | Not yet implemented |
//!
//! ## Dependency on `pulldown-latex`
//!
//! `pulldown-latex = "0.7.1"` is used for its LaTeX tokenizer to build the
//! [`MathAst`]. The OMML output is generated by our own recursive walker in
//! [`omml`]; the `MathML` path will route through pulldown-latex's native output
//! when implemented.

#![forbid(unsafe_code)]
#![warn(missing_docs)]
#![warn(clippy::pedantic)]
#![allow(clippy::module_name_repetitions)]

pub mod ast;
pub mod error;
pub mod interpolation;
pub mod omml;
pub mod parser;

use std::collections::HashMap;
use std::sync::Arc;

pub use ast::{AccentKind, MathAst, MathMode, MathNode};
pub use error::{MathDiagnostic, MathRendererError};

use slideforge_plugin_api::{MathError, MathOutputFormat, MathRenderer};
use slideforge_types::MathNode as TypesMathNode;

/// The built-in math renderer for slideforge.
///
/// Implements [`MathRenderer`] from `slideforge-plugin-api`. Registered with
/// the [`slideforge_plugin_api::PluginRegistry`] at process start.
///
/// ## Variable context
///
/// Math expressions may contain `@{var}` references. These are resolved via the
/// `vars` map passed to [`MathRendererImpl::with_vars`]. When no vars are needed
/// call [`MathRendererImpl::new`].
pub struct MathRendererImpl {
    /// Variable context for `@{var}` substitution. Keys are variable names;
    /// values are their string representations.
    vars: HashMap<Arc<str>, Arc<str>>,
}

impl MathRendererImpl {
    /// Construct a new [`MathRendererImpl`] with an empty variable context.
    #[must_use]
    pub fn new() -> Self {
        MathRendererImpl {
            vars: HashMap::new(),
        }
    }

    /// Construct a new [`MathRendererImpl`] with a pre-populated variable context.
    #[must_use]
    pub fn with_vars(vars: HashMap<Arc<str>, Arc<str>>) -> Self {
        MathRendererImpl { vars }
    }

    /// Parse a raw LaTeX string into a [`MathAst`].
    ///
    /// Runs `@{var}` substitution first, then the LaTeX parser.
    ///
    /// # Errors
    ///
    /// Returns the public [`MathError::SyntaxError`] if parsing fails
    /// (after accumulating all diagnostics).
    pub fn parse(
        &self,
        latex: &str,
        mode: MathMode,
        span: slideforge_types::SourceSpan,
    ) -> Result<MathAst, MathError> {
        // Step 1: resolve @{var} interpolations
        let (substituted, interp_diags) =
            interpolation::substitute(latex, &self.vars, &span);

        if !interp_diags.is_empty() {
            let messages: Vec<String> = interp_diags
                .iter()
                .map(|d| d.error.to_string())
                .collect();
            return Err(MathError::SyntaxError {
                message: messages.join("; "),
            });
        }

        // Step 2: parse LaTeX → MathAst
        let (ast_opt, parse_diags) = parser::parse(&substituted, mode, span);

        if !parse_diags.is_empty() {
            let messages: Vec<String> = parse_diags
                .iter()
                .map(|d| d.error.to_string())
                .collect();
            return Err(MathError::SyntaxError {
                message: messages.join("; "),
            });
        }

        ast_opt.ok_or_else(|| MathError::SyntaxError {
            message: "parser returned no AST".to_owned(),
        })
    }

    /// Render a [`TypesMathNode`] to OMML bytes (full pipeline).
    ///
    /// Calls interpolation → parse → [`omml::render`].
    ///
    /// # Errors
    ///
    /// Returns [`MathError`] on parse or render failure.
    pub fn render_omml(&self, node: &TypesMathNode) -> Result<Vec<u8>, MathError> {
        let mode = if node.display {
            MathMode::Display
        } else {
            MathMode::Inline
        };
        let ast = self.parse(&node.latex, mode, node.span.clone())?;
        omml::render(&ast).map_err(|e| MathError::RenderError {
            message: e.to_string(),
        })
    }
}

impl Default for MathRendererImpl {
    fn default() -> Self {
        Self::new()
    }
}

impl MathRenderer for MathRendererImpl {
    #[allow(clippy::unnecessary_literal_bound)]
    fn id(&self) -> &str {
        "pulldown-latex"
    }

    fn render(&self, node: &TypesMathNode, format: MathOutputFormat) -> Result<Vec<u8>, MathError> {
        match format {
            MathOutputFormat::Omml => self.render_omml(node),
            MathOutputFormat::MathMl | MathOutputFormat::Pdf => {
                Err(MathError::UnsupportedFormat { format })
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use slideforge_plugin_api::MathError;
    use slideforge_types::{MathNode as TypesMathNode, SourceSpan};

    // ─────────────────────────────────────────────────────────────────────────
    // BC-5.29.005 — MathRendererImpl public API
    // ─────────────────────────────────────────────────────────────────────────

    fn inline_node(latex: &str) -> TypesMathNode {
        TypesMathNode::inline(Arc::from(latex), SourceSpan::default())
    }

    fn display_node(latex: &str) -> TypesMathNode {
        TypesMathNode::display(Arc::from(latex), SourceSpan::default())
    }

    /// parse() succeeds for a valid inline expression and returns the correct mode.
    #[test]
    fn test_bc_5_29_005_math_renderer_parse_inline() {
        let renderer = MathRendererImpl::new();
        let result = renderer.parse("E=mc^2", MathMode::Inline, SourceSpan::default());
        let ast = result.expect("parse should succeed for valid LaTeX");
        assert_eq!(ast.mode, MathMode::Inline);
        assert!(!ast.nodes.is_empty(), "AST should not be empty");
    }

    /// render_omml() succeeds for a valid node and returns non-empty bytes.
    #[test]
    fn test_bc_5_29_005_math_renderer_render_omml() {
        let renderer = MathRendererImpl::new();
        let node = inline_node("x^2");
        let result = renderer.render_omml(&node);
        let bytes = result.expect("render_omml should succeed for x^2");
        assert!(!bytes.is_empty(), "OMML output must not be empty");
        let xml = String::from_utf8(bytes).expect("OMML must be valid UTF-8");
        assert!(xml.contains("<m:oMath>"), "inline output must contain <m:oMath>");
    }

    /// render(node, MathMl) returns UnsupportedFormat.
    #[test]
    fn test_bc_5_29_005_mathml_stub_returns_not_implemented() {
        let renderer = MathRendererImpl::new();
        let node = inline_node("x");
        let result = renderer.render(&node, MathOutputFormat::MathMl);
        assert!(
            matches!(result, Err(MathError::UnsupportedFormat { format: MathOutputFormat::MathMl })),
            "expected UnsupportedFormat(MathMl), got: {result:?}"
        );
    }

    /// render(node, Pdf) returns UnsupportedFormat.
    #[test]
    fn test_bc_5_29_005_pdf_paths_stub_returns_not_implemented() {
        let renderer = MathRendererImpl::new();
        let node = inline_node("x");
        let result = renderer.render(&node, MathOutputFormat::Pdf);
        assert!(
            matches!(result, Err(MathError::UnsupportedFormat { format: MathOutputFormat::Pdf })),
            "expected UnsupportedFormat(Pdf), got: {result:?}"
        );
    }

    /// display_node renders with <m:oMathPara> wrapper.
    #[test]
    fn test_bc_5_29_005_display_mode_para_wrapper() {
        let renderer = MathRendererImpl::new();
        let node = display_node(r"\sum_{i=0}^n i");
        let result = renderer.render_omml(&node);
        let bytes = result.expect("render_omml should succeed");
        let xml = String::from_utf8(bytes).expect("valid UTF-8");
        assert!(xml.contains("<m:oMathPara>"), "display mode must use <m:oMathPara>");
    }

    /// MathRendererImpl implements MathRenderer trait (Send + Sync).
    #[test]
    fn test_bc_5_29_005_is_send_sync() {
        fn assert_send_sync<T: Send + Sync>() {}
        assert_send_sync::<MathRendererImpl>();
    }

    /// id() returns "pulldown-latex".
    #[test]
    fn test_bc_5_29_005_renderer_id() {
        let renderer = MathRendererImpl::new();
        assert_eq!(renderer.id(), "pulldown-latex");
    }

    /// with_vars() substitutes @{var} in an expression before parsing.
    #[test]
    fn test_bc_5_29_005_with_vars_substitution() {
        let mut vars = HashMap::new();
        vars.insert(Arc::from("n"), Arc::from("10"));
        let renderer = MathRendererImpl::with_vars(vars);
        let result = renderer.parse(r"\sum_{i=0}^{@{n}}", MathMode::Inline, SourceSpan::default());
        // After substitution the source becomes \sum_{i=0}^{10} which is valid
        let ast = result.expect("parse with vars should succeed");
        assert!(!ast.nodes.is_empty());
    }
}
