//! `slideforge-math` — math rendering engine for slideforge.
//!
//! This crate implements the [`MathRenderer`] plugin surface from
//! `slideforge-plugin-api`. It is the built-in LaTeX → OMML/MathML renderer
//! shipped with slideforge.
//!
//! ## Pipeline
//!
//! ```text
//! MathNode (raw LaTeX + span)
//!   └─► substitute()  — @{var} interpolation
//!         └─► parse()    — LaTeX → MathAst
//!               └─► omml::render() / mathml::render_mathml() / pdf_paths::render_pdf_paths()
//!                     └─► Vec<u8>  — OMML, MathML, or SVG path bytes
//! ```
//!
//! ## Supported outputs
//!
//! | Format | Status |
//! |--------|--------|
//! | [`MathOutputFormat::Omml`] | Implemented (STORY-029) |
//! | [`MathOutputFormat::MathMl`] | Implemented (STORY-030) |
//! | [`MathOutputFormat::Pdf`] | Implemented (STORY-030) |
//!
//! ## Implementation approach
//!
//! The [`parser`] module is a hand-written recursive-descent parser that
//! converts the supported LaTeX subset directly to [`MathAst`]. The OMML
//! output is generated by our own recursive walker in [`omml`]. The `MathML`
//! path lives in [`mathml`] and the PDF vector-path renderer lives in
//! [`pdf_paths`]; both are implemented in STORY-030.
//! `pulldown-latex` is NOT a dependency — v1.0 uses only the supported subset
//! defined by the behavioral contracts.

#![forbid(unsafe_code)]
#![warn(missing_docs)]
#![warn(clippy::pedantic)]
#![allow(clippy::module_name_repetitions)]

pub mod ast;
pub mod error;
pub mod interpolation;
pub mod mathml;
pub mod omml;
pub mod parser;
pub mod pdf_paths;
pub mod symbols;

use std::collections::HashMap;
use std::sync::Arc;

pub use ast::{AccentKind, MathAst, MathMode, MathNode};
pub use error::{MathDiagnostic, MathRendererError};
pub use pdf_paths::SvgPaths;

use slideforge_plugin_api::{MathError, MathOutputFormat, MathRenderer};
use slideforge_types::MathNode as TypesMathNode;

/// The built-in math renderer for slideforge.
///
/// Implements [`MathRenderer`] from `slideforge-plugin-api`. Registered with
/// the [`slideforge_plugin_api::PluginRegistry`] at process start.
///
/// ## Variable context
///
/// Math expressions may contain `@{var}` references. These are resolved via the
/// `vars` map passed to [`MathRendererImpl::with_vars`]. When no vars are needed
/// call [`MathRendererImpl::new`].
pub struct MathRendererImpl {
    /// Variable context for `@{var}` substitution. Keys are variable names;
    /// values are their string representations.
    vars: HashMap<Arc<str>, Arc<str>>,
}

impl MathRendererImpl {
    /// Construct a new [`MathRendererImpl`] with an empty variable context.
    #[must_use]
    pub fn new() -> Self {
        MathRendererImpl {
            vars: HashMap::new(),
        }
    }

    /// Construct a new [`MathRendererImpl`] with a pre-populated variable context.
    #[must_use]
    pub fn with_vars(vars: HashMap<Arc<str>, Arc<str>>) -> Self {
        MathRendererImpl { vars }
    }

    /// Parse a raw LaTeX string into a [`MathAst`].
    ///
    /// Runs `@{var}` substitution first, then the LaTeX parser.
    ///
    /// # Errors
    ///
    /// Returns the public [`MathError::SyntaxError`] if parsing fails
    /// (after accumulating all diagnostics).
    pub fn parse(
        &self,
        latex: &str,
        mode: MathMode,
        span: slideforge_types::SourceSpan,
    ) -> Result<MathAst, MathError> {
        // Step 1: resolve @{var} interpolations.
        // NOTE: we always proceed to parsing even if interpolation produced
        // diagnostics (FINDING-010: error accumulation must span both phases).
        let (substituted, interp_diags) = interpolation::substitute(latex, &self.vars, &span);

        // Step 2: parse LaTeX → MathAst (runs even when interp had errors)
        let (ast_opt, parse_diags) = parser::parse(&substituted, mode, span);

        // Step 3: combine both diagnostic lists
        let all_diags: Vec<_> = interp_diags.into_iter().chain(parse_diags).collect();

        if !all_diags.is_empty() {
            let messages: Vec<String> = all_diags.iter().map(|d| d.error.to_string()).collect();
            return Err(MathError::SyntaxError {
                message: messages.join("; "),
            });
        }

        ast_opt.ok_or_else(|| MathError::SyntaxError {
            message: "parser returned no AST".to_owned(),
        })
    }

    /// Render a [`TypesMathNode`] to OMML bytes (full pipeline).
    ///
    /// Calls interpolation → parse → [`omml::render`].
    ///
    /// # Errors
    ///
    /// Returns [`MathError`] on parse or render failure.
    pub fn render_omml(&self, node: &TypesMathNode) -> Result<Vec<u8>, MathError> {
        let mode = if node.display {
            MathMode::Display
        } else {
            MathMode::Inline
        };
        let ast = self.parse(&node.latex, mode, node.span.clone())?;
        omml::render(&ast).map_err(|e| match e {
            MathRendererError::EmptyCommandName => MathError::EmptyCommandName,
            MathRendererError::UnsupportedSymbol { name } => MathError::UnsupportedSymbol {
                name: name.to_string(),
            },
            other => MathError::RenderError {
                message: other.to_string(),
            },
        })
    }
}

impl Default for MathRendererImpl {
    fn default() -> Self {
        Self::new()
    }
}

impl MathRenderer for MathRendererImpl {
    #[allow(clippy::unnecessary_literal_bound)]
    fn id(&self) -> &str {
        "slideforge-builtin"
    }

    fn render(&self, node: &TypesMathNode, format: MathOutputFormat) -> Result<Vec<u8>, MathError> {
        match format {
            MathOutputFormat::Omml => self.render_omml(node),
            MathOutputFormat::MathMl => {
                let mode = if node.display {
                    MathMode::Display
                } else {
                    MathMode::Inline
                };
                let ast = self.parse(&node.latex, mode, node.span.clone())?;
                let html = mathml::render_mathml(&ast)?;
                Ok(html.into_bytes())
            },
            MathOutputFormat::Pdf => {
                let mode = if node.display {
                    MathMode::Display
                } else {
                    MathMode::Inline
                };
                let ast = self.parse(&node.latex, mode, node.span.clone())?;
                let paths = pdf_paths::render_pdf_paths(&ast)?;
                Ok(paths.0.into_bytes())
            },
        }
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;
    use slideforge_types::{MathNode as TypesMathNode, SourceSpan};

    // ─────────────────────────────────────────────────────────────────────────
    // BC-1.10.003 — MathRendererImpl public API
    // ─────────────────────────────────────────────────────────────────────────

    fn inline_node(latex: &str) -> TypesMathNode {
        TypesMathNode::inline(Arc::from(latex), SourceSpan::default())
    }

    fn display_node(latex: &str) -> TypesMathNode {
        TypesMathNode::display(Arc::from(latex), SourceSpan::default())
    }

    /// `parse()` succeeds for a valid inline expression and returns the correct mode.
    #[test]
    fn test_bc_1_10_003_math_renderer_parse_inline() {
        let renderer = MathRendererImpl::new();
        let result = renderer.parse("E=mc^2", MathMode::Inline, SourceSpan::default());
        let ast = result.expect("parse should succeed for valid LaTeX");
        assert_eq!(ast.mode, MathMode::Inline);
        assert!(!ast.nodes.is_empty(), "AST should not be empty");
    }

    /// `render_omml()` succeeds for a valid node and returns non-empty bytes.
    #[test]
    fn test_bc_1_10_003_math_renderer_render_omml() {
        let renderer = MathRendererImpl::new();
        let node = inline_node("x^2");
        let result = renderer.render_omml(&node);
        let bytes = result.expect("render_omml should succeed for x^2");
        assert!(!bytes.is_empty(), "OMML output must not be empty");
        let xml = String::from_utf8(bytes).expect("OMML must be valid UTF-8");
        // Root element is <m:oMath xmlns:m="..."> — check prefix not bare tag
        assert!(
            xml.contains("<m:oMath"),
            "inline output must contain <m:oMath>"
        );
    }

    /// `render(node, MathMl)` dispatches through the trait to `render_mathml` and
    /// returns a UTF-8 string containing the `MathML` namespace and `display="inline"`.
    ///
    /// RED GATE: fails until STORY-030 implements `render_mathml` (todo!() panics).
    #[test]
    fn test_bc_1_10_003_renderer_dispatches_to_mathml_for_html() {
        let renderer = MathRendererImpl::new();
        let node = inline_node("x");
        let bytes = renderer
            .render(&node, MathOutputFormat::MathMl)
            .expect("render(MathMl) must succeed for 'x'");
        let output = String::from_utf8(bytes).expect("MathML output must be valid UTF-8");
        assert!(
            output.contains("http://www.w3.org/1998/Math/MathML"),
            "MathML output must contain namespace URI; got: {output}"
        );
        assert!(
            output.contains(r#"display="inline""#),
            "inline MathML must have display=\"inline\"; got: {output}"
        );
    }

    /// `render(node, Pdf)` dispatches through the trait to `render_pdf_paths` and
    /// returns bytes that, as a string, contain an SVG root element and no `<text>`.
    ///
    /// RED GATE: fails until STORY-030 implements `render_pdf_paths` (todo!() panics).
    #[test]
    fn test_bc_1_10_003_renderer_dispatches_to_pdf_paths_for_pdf() {
        let renderer = MathRendererImpl::new();
        let node = inline_node("x");
        let bytes = renderer
            .render(&node, MathOutputFormat::Pdf)
            .expect("render(Pdf) must succeed for 'x'");
        let output = String::from_utf8(bytes).expect("PDF paths output must be valid UTF-8");
        assert!(
            output.contains("<svg") || output.contains("<?xml"),
            "PDF path output must be an SVG document; got: {}",
            &output[..output.len().min(120)]
        );
        assert!(
            !output.contains("<text"),
            "PDF path SVG must contain no <text> elements; got: {}",
            &output[..output.len().min(400)]
        );
    }

    /// `display_node` renders with `<m:oMathPara>` wrapper.
    #[test]
    fn test_bc_1_10_003_display_mode_para_wrapper() {
        let renderer = MathRendererImpl::new();
        let node = display_node(r"\sum_{i=0}^n i");
        let result = renderer.render_omml(&node);
        let bytes = result.expect("render_omml should succeed");
        let xml = String::from_utf8(bytes).expect("valid UTF-8");
        // Root element is <m:oMathPara xmlns:m="..."> — check prefix not bare tag
        assert!(
            xml.contains("<m:oMathPara"),
            "display mode must use <m:oMathPara>"
        );
    }

    /// `MathRendererImpl` implements `MathRenderer` trait (`Send + Sync`).
    #[test]
    fn test_bc_1_10_003_is_send_sync() {
        fn assert_send_sync<T: Send + Sync>() {}
        assert_send_sync::<MathRendererImpl>();
    }

    /// `id()` returns the stable plugin identifier for this math renderer.
    ///
    /// The built-in renderer is identified as `"slideforge-builtin"` because
    /// it uses the project's own hand-written LaTeX subset parser — not the
    /// `pulldown-latex` crate (which is not a dependency).
    #[test]
    fn test_bc_1_10_003_renderer_id() {
        let renderer = MathRendererImpl::new();
        assert_eq!(renderer.id(), "slideforge-builtin");
    }

    /// `with_vars()` substitutes `@{var}` in an expression before parsing.
    #[test]
    fn test_bc_1_10_003_with_vars_substitution() {
        let mut vars = HashMap::new();
        vars.insert(Arc::from("n"), Arc::from("10"));
        let renderer = MathRendererImpl::with_vars(vars);
        let result = renderer.parse(
            r"\sum_{i=0}^{@{n}}",
            MathMode::Inline,
            SourceSpan::default(),
        );
        // After substitution the source becomes \sum_{i=0}^{10} which is valid
        let ast = result.expect("parse with vars should succeed");
        assert!(!ast.nodes.is_empty());
    }

    // ─────────────────────────────────────────────────────────────────────────
    // FINDING-010 — Error accumulation: both interpolation AND parse diagnostics
    // ─────────────────────────────────────────────────────────────────────────

    /// `parse()` with both an undefined `@{var}` AND an unsupported `\command` must
    /// return an error whose message contains BOTH diagnostics (not just the first).
    #[test]
    fn test_finding_010_both_interp_and_parse_errors_returned() {
        let renderer = MathRendererImpl::new(); // empty vars map
        let result = renderer.parse(
            r"@{undefined} + \unknowncmd",
            MathMode::Inline,
            SourceSpan::default(),
        );
        // Must be an error (both diagnostics)
        let err = result.expect_err("expected error for undefined var + unsupported command");
        let msg = err.to_string();
        // The message should mention the undefined variable
        assert!(
            msg.contains("undefined")
                || msg.contains("missing")
                || msg.contains("UndefinedVariable"),
            "error message must reference the undefined variable; got: {msg}"
        );
        // The message should also mention the unsupported command
        assert!(
            msg.contains("unknowncmd") || msg.contains("E-EXP-006") || msg.contains("unsupported"),
            "error message must reference the unsupported command; got: {msg}"
        );
    }
}
