//! `MathML` renderer for `slideforge-math`.
//!
//! Converts a [`MathAst`] to a `<math>` element string compliant with
//! `MathML` Core Level 1 (`http://www.w3.org/1998/Math/MathML`). Intended for
//! consumption by the HTML exporter (STORY-046) and the web preview server
//! (STORY-047).
//!
//! ## Accessibility
//!
//! Every `<math>` element produced by [`render_mathml`] includes an
//! `aria-label` attribute with a plain-text description of the expression,
//! generated by [`ast_to_aria_label`]. This satisfies WCAG AA screen-reader
//! requirements (AC-002).
//!
//! ## Display mode
//!
//! Inline math (`MathMode::Inline`) produces `display="inline"` on the root
//! `<math>` element; display math (`MathMode::Display`) produces
//! `display="block"`.

use quick_xml::{
    Writer,
    events::{BytesEnd, BytesStart, BytesText, Event},
};
use slideforge_plugin_api::MathError;

use crate::MathAst;
use crate::ast::{MathMode, MathNode};
use crate::symbols::{greek_to_unicode_char, operator_to_unicode_char, symbol_to_unicode_char};

/// The W3C `MathML` namespace URI.
const MATHML_NS: &str = "http://www.w3.org/1998/Math/MathML";

/// Render a [`MathAst`] to a `MathML` `<math>` element string.
///
/// The returned string is a complete, self-contained `MathML` fragment with:
/// - `xmlns="http://www.w3.org/1998/Math/MathML"` namespace declaration
/// - `display="inline"` or `display="block"` from [`crate::MathMode`]
/// - `aria-label` generated by [`ast_to_aria_label`]
///
/// # Errors
///
/// Returns [`MathError::RenderError`] if the AST cannot be serialised to
/// `MathML`.
pub fn render_mathml(ast: &MathAst) -> Result<String, MathError> {
    let mut buf: Vec<u8> = Vec::with_capacity(512);
    let mut writer = Writer::new(&mut buf);

    let aria_label = ast_to_aria_label(ast);

    // Build root <math> element with namespace, display mode, and aria-label
    let display_val = match ast.mode {
        MathMode::Inline => "inline",
        MathMode::Display => "block",
    };

    let mut root = BytesStart::new("math");
    root.push_attribute(("xmlns", MATHML_NS));
    root.push_attribute(("display", display_val));
    root.push_attribute(("aria-label", aria_label.as_str()));

    writer
        .write_event(Event::Start(root))
        .map_err(|e| MathError::RenderError {
            message: e.to_string(),
        })?;

    // Wrap all top-level nodes in an <mrow>
    writer
        .write_event(Event::Start(BytesStart::new("mrow")))
        .map_err(|e| MathError::RenderError {
            message: e.to_string(),
        })?;

    for node in &ast.nodes {
        write_node(&mut writer, node).map_err(|e| MathError::RenderError {
            message: e.to_string(),
        })?;
    }

    writer
        .write_event(Event::End(BytesEnd::new("mrow")))
        .map_err(|e| MathError::RenderError {
            message: e.to_string(),
        })?;

    writer
        .write_event(Event::End(BytesEnd::new("math")))
        .map_err(|e| MathError::RenderError {
            message: e.to_string(),
        })?;

    String::from_utf8(buf).map_err(|e| MathError::RenderError {
        message: e.to_string(),
    })
}

/// Classify a text token as a `MathML` element tag:
/// - Digits (all chars are ASCII digits) → `"mn"` (number)
/// - Operators (+, -, =, *, /, <, >, ≤, ≥, etc.) → `"mo"` (operator)
/// - Everything else → `"mi"` (identifier)
fn classify_text(s: &str) -> &'static str {
    if s.chars().all(|c| c.is_ascii_digit() || c == '.') {
        "mn"
    } else if is_operator(s) {
        "mo"
    } else {
        "mi"
    }
}

/// Return `true` if the token is a recognised math operator.
fn is_operator(s: &str) -> bool {
    matches!(
        s,
        "+" | "-"
            | "="
            | "*"
            | "/"
            | "<"
            | ">"
            | "≤"
            | "≥"
            | "≠"
            | "±"
            | "×"
            | "÷"
            | "·"
            | "∈"
            | "∉"
            | "⊂"
            | "⊃"
            | "∪"
            | "∩"
            | ","
            | ";"
            | ":"
            | "!"
            | "|"
    )
}

/// Write a single [`MathNode`] as `MathML` into `writer`.
fn write_node(writer: &mut Writer<&mut Vec<u8>>, node: &MathNode) -> Result<(), quick_xml::Error> {
    match node {
        MathNode::Text(s) => {
            let tag = classify_text(s);
            writer.write_event(Event::Start(BytesStart::new(tag)))?;
            writer.write_event(Event::Text(BytesText::new(s)))?;
            writer.write_event(Event::End(BytesEnd::new(tag)))?;
        },

        MathNode::TextRun(s) => {
            // Upright/roman text in math — rendered as <mtext>
            writer.write_event(Event::Start(BytesStart::new("mtext")))?;
            writer.write_event(Event::Text(BytesText::new(s)))?;
            writer.write_event(Event::End(BytesEnd::new("mtext")))?;
        },

        MathNode::Superscript { base, sup } => {
            writer.write_event(Event::Start(BytesStart::new("msup")))?;
            write_node(writer, base)?;
            write_node(writer, sup)?;
            writer.write_event(Event::End(BytesEnd::new("msup")))?;
        },

        MathNode::Subscript { base, sub } => {
            writer.write_event(Event::Start(BytesStart::new("msub")))?;
            write_node(writer, base)?;
            write_node(writer, sub)?;
            writer.write_event(Event::End(BytesEnd::new("msub")))?;
        },

        MathNode::Fraction { num, denom } => {
            writer.write_event(Event::Start(BytesStart::new("mfrac")))?;
            write_node(writer, num)?;
            write_node(writer, denom)?;
            writer.write_event(Event::End(BytesEnd::new("mfrac")))?;
        },

        MathNode::Sqrt {
            index: None,
            radicand,
        } => {
            writer.write_event(Event::Start(BytesStart::new("msqrt")))?;
            write_node(writer, radicand)?;
            writer.write_event(Event::End(BytesEnd::new("msqrt")))?;
        },

        MathNode::Sqrt {
            index: Some(n),
            radicand,
        } => {
            writer.write_event(Event::Start(BytesStart::new("mroot")))?;
            write_node(writer, radicand)?;
            write_node(writer, n)?;
            writer.write_event(Event::End(BytesEnd::new("mroot")))?;
        },

        MathNode::Operator(name) => {
            // Map operator name to Unicode symbol where possible via the shared
            // canonical symbols table (BC-1.10.003 inv. 6: cross-renderer equivalence).
            // Text-based operators (lim, max, etc.) have no Unicode-symbol mapping
            // and use the command name as literal text.
            // Empty name returns error.
            if name.is_empty() {
                return Err(quick_xml::Error::Io(std::sync::Arc::new(
                    std::io::Error::other("empty operator command name"),
                )));
            }
            let sym_str;
            let sym: &str = if let Some(ch) = operator_to_unicode_char(name) {
                sym_str = ch.to_string();
                &sym_str
            } else {
                // Text-based operator or other name used as literal text
                name
            };
            writer.write_event(Event::Start(BytesStart::new("mo")))?;
            writer.write_event(Event::Text(BytesText::new(sym)))?;
            writer.write_event(Event::End(BytesEnd::new("mo")))?;
        },

        MathNode::Greek(name) => {
            // All Greek glyphs resolved through the shared canonical symbols table.
            // Empty name returns error; unrecognised name returns error.
            if name.is_empty() {
                return Err(quick_xml::Error::Io(std::sync::Arc::new(
                    std::io::Error::other("empty Greek command name"),
                )));
            }
            let ch = greek_to_unicode_char(name).ok_or_else(|| {
                quick_xml::Error::Io(std::sync::Arc::new(std::io::Error::other(format!(
                    "unsupported Greek command: {name}"
                ))))
            })?;
            let sym = ch.to_string();
            writer.write_event(Event::Start(BytesStart::new("mi")))?;
            writer.write_event(Event::Text(BytesText::new(&sym)))?;
            writer.write_event(Event::End(BytesEnd::new("mi")))?;
        },

        MathNode::Symbol(name) => {
            // All symbols resolved through the shared canonical symbols table.
            // Empty name returns error; unrecognised name returns error.
            if name.is_empty() {
                return Err(quick_xml::Error::Io(std::sync::Arc::new(
                    std::io::Error::other("empty symbol command name"),
                )));
            }
            let ch = symbol_to_unicode_char(name).ok_or_else(|| {
                quick_xml::Error::Io(std::sync::Arc::new(std::io::Error::other(format!(
                    "unsupported symbol command: {name}"
                ))))
            })?;
            let sym = ch.to_string();
            writer.write_event(Event::Start(BytesStart::new("mo")))?;
            writer.write_event(Event::Text(BytesText::new(&sym)))?;
            writer.write_event(Event::End(BytesEnd::new("mo")))?;
        },

        MathNode::Accent { kind, inner } => {
            // Use <mover> with appropriate accent character
            let accent_char = crate::ast::AccentKind::accent_char(kind);
            writer.write_event(Event::Start(BytesStart::new("mover")))?;
            write_node(writer, inner)?;
            writer.write_event(Event::Start(BytesStart::new("mo")))?;
            writer.write_event(Event::Text(BytesText::new(accent_char)))?;
            writer.write_event(Event::End(BytesEnd::new("mo")))?;
            writer.write_event(Event::End(BytesEnd::new("mover")))?;
        },

        MathNode::Group(nodes) => {
            writer.write_event(Event::Start(BytesStart::new("mrow")))?;
            for n in nodes {
                write_node(writer, n)?;
            }
            writer.write_event(Event::End(BytesEnd::new("mrow")))?;
        },

        MathNode::Delimiter { left, right, inner } => {
            // Produce <mrow><mo>left</mo>...inner...<mo>right</mo></mrow>
            writer.write_event(Event::Start(BytesStart::new("mrow")))?;
            writer.write_event(Event::Start(BytesStart::new("mo")))?;
            writer.write_event(Event::Text(BytesText::new(left)))?;
            writer.write_event(Event::End(BytesEnd::new("mo")))?;
            for n in inner {
                write_node(writer, n)?;
            }
            writer.write_event(Event::Start(BytesStart::new("mo")))?;
            writer.write_event(Event::Text(BytesText::new(right)))?;
            writer.write_event(Event::End(BytesEnd::new("mo")))?;
            writer.write_event(Event::End(BytesEnd::new("mrow")))?;
        },

        MathNode::Align(rows) => {
            // Render as <mtable> with rows and cells
            writer.write_event(Event::Start(BytesStart::new("mtable")))?;
            for row in rows {
                writer.write_event(Event::Start(BytesStart::new("mtr")))?;
                writer.write_event(Event::Start(BytesStart::new("mtd")))?;
                for n in row {
                    write_node(writer, n)?;
                }
                writer.write_event(Event::End(BytesEnd::new("mtd")))?;
                writer.write_event(Event::End(BytesEnd::new("mtr")))?;
            }
            writer.write_event(Event::End(BytesEnd::new("mtable")))?;
        },

        MathNode::Cases(cases) => {
            // Render cases as <mrow><mo>{</mo><mtable>...</mtable></mrow>
            writer.write_event(Event::Start(BytesStart::new("mrow")))?;
            writer.write_event(Event::Start(BytesStart::new("mo")))?;
            writer.write_event(Event::Text(BytesText::new("{")))?;
            writer.write_event(Event::End(BytesEnd::new("mo")))?;
            writer.write_event(Event::Start(BytesStart::new("mtable")))?;
            for (cond, result) in cases {
                writer.write_event(Event::Start(BytesStart::new("mtr")))?;
                writer.write_event(Event::Start(BytesStart::new("mtd")))?;
                for n in result {
                    write_node(writer, n)?;
                }
                writer.write_event(Event::End(BytesEnd::new("mtd")))?;
                writer.write_event(Event::Start(BytesStart::new("mtd")))?;
                for n in cond {
                    write_node(writer, n)?;
                }
                writer.write_event(Event::End(BytesEnd::new("mtd")))?;
                writer.write_event(Event::End(BytesEnd::new("mtr")))?;
            }
            writer.write_event(Event::End(BytesEnd::new("mtable")))?;
            writer.write_event(Event::End(BytesEnd::new("mrow")))?;
        },

        MathNode::Space => {
            // Render as thin space operator
            writer.write_event(Event::Start(BytesStart::new("mspace")))?;
            writer.write_event(Event::End(BytesEnd::new("mspace")))?;
        },
    }

    Ok(())
}

/// Derive a plain-text aria label from a [`MathAst`].
///
/// The label is a best-effort heuristic for the v1.0 supported LaTeX subset.
/// It is used as the `aria-label` attribute on the root `<math>` element
/// produced by [`render_mathml`].
///
/// For example, `E = mc^2` yields `"E equals m times c squared"`.
///
/// Empty AST (no nodes) yields `"empty math expression"` rather than an empty
/// string, so that the `aria-label` attribute is always non-empty (finding I4).
///
/// This function is pure (no I/O, no side effects) and is exported so that
/// the PDF and PPTX exporters can attach the same accessible label to
/// embedded math objects.
#[must_use]
pub fn ast_to_aria_label(ast: &MathAst) -> String {
    let mut parts: Vec<String> = Vec::new();
    for node in &ast.nodes {
        node_to_label(node, &mut parts);
    }
    // Insert "times" between adjacent single-letter math identifiers.
    //
    // AC-002: `E = mc^2` must yield "E equals m times c squared", not
    // "E equals m c squared".  Two consecutive label parts are "adjacent
    // identifiers" when both are single ASCII letters (math variables).
    let parts = insert_times_between_adjacent_identifiers(parts);

    if parts.is_empty() {
        // Finding I4: empty AST must not produce aria-label="".
        "empty math expression".to_owned()
    } else {
        parts.join(" ")
    }
}

/// Returns `true` if a label part represents a single-letter math identifier.
///
/// Only single ASCII-letter parts (a–z, A–Z) are considered identifiers for
/// the purposes of "times" insertion.  Operator words like "equals", "plus",
/// numbers, and Greek-letter names (multi-char) are not identifiers.
fn is_single_letter_identifier(s: &str) -> bool {
    s.len() == 1 && s.chars().next().is_some_and(|c| c.is_ascii_alphabetic())
}

/// Walk `parts` and insert "times" between any two consecutive parts that are
/// both single-letter math identifiers (e.g. `["m", "c"]` → `["m", "times", "c"]`).
fn insert_times_between_adjacent_identifiers(parts: Vec<String>) -> Vec<String> {
    if parts.len() < 2 {
        return parts;
    }
    let mut result = Vec::with_capacity(parts.len() * 2);
    let mut iter = parts.into_iter().peekable();
    while let Some(part) = iter.next() {
        let is_id = is_single_letter_identifier(&part);
        result.push(part);
        if is_id
            && let Some(next) = iter.peek()
            && is_single_letter_identifier(next)
        {
            result.push("times".to_owned());
        }
    }
    result
}

/// Recursively produce label parts from a [`MathNode`].
fn node_to_label(node: &MathNode, parts: &mut Vec<String>) {
    match node {
        MathNode::Text(s) => {
            let spoken = text_to_spoken(s);
            parts.push(spoken.to_owned());
        },

        MathNode::TextRun(s) => {
            parts.push(s.to_string());
        },

        MathNode::Superscript { base, sup } => {
            // Check if sup is a simple number for "squared"/"cubed" shortcut
            let sup_text = extract_simple_text(sup);
            node_to_label(base, parts);
            match sup_text {
                Some("2") => parts.push("squared".to_owned()),
                Some("3") => parts.push("cubed".to_owned()),
                Some(n) => {
                    parts.push("to the".to_owned());
                    parts.push((*n).to_owned());
                },
                None => {
                    parts.push("to the power".to_owned());
                    node_to_label(sup, parts);
                },
            }
        },

        MathNode::Subscript { base, sub } => {
            node_to_label(base, parts);
            parts.push("sub".to_owned());
            node_to_label(sub, parts);
        },

        MathNode::Fraction { num, denom } => {
            node_to_label(num, parts);
            parts.push("over".to_owned());
            node_to_label(denom, parts);
        },

        MathNode::Sqrt {
            index: None,
            radicand,
        } => {
            parts.push("square root of".to_owned());
            node_to_label(radicand, parts);
        },

        MathNode::Sqrt {
            index: Some(idx),
            radicand,
        } => {
            node_to_label(idx, parts);
            parts.push("th root of".to_owned());
            node_to_label(radicand, parts);
        },

        MathNode::Operator(name) => {
            parts.push(operator_spoken(name).to_owned());
        },

        MathNode::Greek(name) => {
            parts.push(name.to_string());
        },

        MathNode::Symbol(name) => {
            parts.push(symbol_spoken(name).to_owned());
        },

        MathNode::Accent { kind, inner } => {
            use crate::ast::AccentKind;
            let accent_word = match kind {
                AccentKind::Hat => "hat",
                AccentKind::Bar => "bar",
                AccentKind::Tilde => "tilde",
                AccentKind::Vec => "vector",
                AccentKind::Dot => "dot",
                AccentKind::Ddot => "double dot",
            };
            parts.push(accent_word.to_owned());
            node_to_label(inner, parts);
        },

        MathNode::Group(nodes) => {
            for n in nodes {
                node_to_label(n, parts);
            }
        },

        MathNode::Delimiter { inner, .. } => {
            for n in inner {
                node_to_label(n, parts);
            }
        },

        MathNode::Align(rows) => {
            for row in rows {
                for n in row {
                    node_to_label(n, parts);
                }
            }
        },

        MathNode::Cases(cases) => {
            for (cond, result) in cases {
                for n in result {
                    node_to_label(n, parts);
                }
                parts.push("if".to_owned());
                for n in cond {
                    node_to_label(n, parts);
                }
            }
        },

        MathNode::Space => {
            // Silent space — do not add a spoken part
        },
    }
}

/// Extract the text content of a simple `MathNode::Text` or `MathNode::Group`
/// containing a single `MathNode::Text`. Returns `None` for complex nodes.
fn extract_simple_text(node: &MathNode) -> Option<&str> {
    match node {
        MathNode::Text(s) => Some(s),
        MathNode::Group(nodes) if nodes.len() == 1 => {
            if let MathNode::Text(s) = &nodes[0] {
                Some(s)
            } else {
                None
            }
        },
        _ => None,
    }
}

/// Map a text token to its spoken English form.
fn text_to_spoken(s: &str) -> &str {
    match s {
        "+" => "plus",
        "-" => "minus",
        "=" => "equals",
        "*" => "times",
        "/" => "divided by",
        "<" => "less than",
        ">" => "greater than",
        "," => "comma",
        _ => s,
    }
}

/// Map an operator command name to its spoken English form.
fn operator_spoken(name: &str) -> &str {
    match name {
        "sum" => "sum",
        "prod" => "product",
        "int" => "integral",
        "oint" => "contour integral",
        "lim" => "limit",
        "max" => "maximum",
        "min" => "minimum",
        "log" => "log",
        "ln" => "natural log",
        "sin" => "sine",
        "cos" => "cosine",
        "tan" => "tangent",
        _ => name,
    }
}

/// Map a symbol command name to its spoken English form.
fn symbol_spoken(name: &str) -> &str {
    match name {
        "cdot" | "times" => "times",
        "div" => "divided by",
        "infty" => "infinity",
        "pm" => "plus or minus",
        "mp" => "minus or plus",
        "leq" | "le" => "less than or equal to",
        "geq" | "ge" => "greater than or equal to",
        "neq" | "ne" => "not equal to",
        "approx" => "approximately",
        "equiv" => "equivalent to",
        "in" => "in",
        "notin" => "not in",
        "subset" => "subset of",
        "supset" => "superset of",
        "cup" => "union",
        "cap" => "intersection",
        "emptyset" => "empty set",
        "forall" => "for all",
        "exists" => "there exists",
        "partial" => "partial",
        "nabla" => "nabla",
        "rightarrow" | "to" => "goes to",
        "leftarrow" => "from",
        "Rightarrow" => "implies",
        "Leftarrow" => "implied by",
        "Leftrightarrow" | "leftrightarrow" => "if and only if",
        "ldots" | "cdots" | "vdots" | "ddots" => "dot dot dot",
        _ => name,
    }
}

// Add accent_char method to AccentKind — placed here as a standalone function
// that delegates, since we cannot add methods to types from other modules
// via impl blocks (we can since AccentKind is in our own crate).

impl crate::ast::AccentKind {
    /// Return the Unicode character used as the accent symbol in `MathML` `<mover>`.
    #[must_use]
    pub fn accent_char(kind: &crate::ast::AccentKind) -> &'static str {
        match kind {
            crate::ast::AccentKind::Hat => "\u{005E}",   // ^
            crate::ast::AccentKind::Bar => "\u{00AF}",   // ¯
            crate::ast::AccentKind::Tilde => "\u{007E}", // ~
            crate::ast::AccentKind::Vec => "\u{2192}",   // →
            crate::ast::AccentKind::Dot => "\u{02D9}",   // ˙
            crate::ast::AccentKind::Ddot => "\u{00A8}",  // ¨
        }
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use std::sync::Arc;

    use super::*;
    use crate::ast::{MathMode, MathNode};

    // ─────────────────────────────────────────────────────────────────────────
    // Helpers
    // ─────────────────────────────────────────────────────────────────────────

    /// Build a minimal [`MathAst`] inline expression.
    fn inline_ast(nodes: Vec<MathNode>) -> MathAst {
        MathAst::new(MathMode::Inline, nodes)
    }

    /// Build a minimal [`MathAst`] display (block) expression.
    fn display_ast(nodes: Vec<MathNode>) -> MathAst {
        MathAst::new(MathMode::Display, nodes)
    }

    /// Walk a string with `quick_xml` and confirm all tags balance.
    ///
    /// Returns `Ok(())` if the XML is well-formed, `Err(msg)` otherwise.
    fn assert_wellformed_xml(xml: &str) -> Result<(), String> {
        use quick_xml::Reader;
        use quick_xml::events::Event;

        let mut reader = Reader::from_str(xml);
        let mut depth: i64 = 0;
        let mut buf = Vec::new();

        loop {
            match reader.read_event_into(&mut buf) {
                Ok(Event::Start(_)) => depth += 1,
                Ok(Event::End(_)) => {
                    depth -= 1;
                    if depth < 0 {
                        return Err(format!("unmatched closing tag in: {xml}"));
                    }
                },
                Ok(Event::Eof) => break,
                Err(e) => return Err(format!("XML parse error: {e}")),
                _ => {},
            }
            buf.clear();
        }

        if depth != 0 {
            return Err(format!("unclosed tags (depth={depth}) in: {xml}"));
        }
        Ok(())
    }

    // ─────────────────────────────────────────────────────────────────────────
    // BC-1.10.003 — AC-001: MathML output for HTML export
    // ─────────────────────────────────────────────────────────────────────────

    /// `render_mathml` for `$x + y$` returns a string containing the `MathML`
    /// root `<math xmlns="http://www.w3.org/1998/Math/MathML"` element, and
    /// contains rendered identifiers `<mi>x</mi>`, `<mi>y</mi>` and the
    /// operator `<mo>+</mo>`.
    ///
    /// RED GATE: fails until `render_mathml` is implemented (`todo!()` panics).
    #[test]
    fn test_bc_1_10_003_mathml_simple_expression() {
        let ast = inline_ast(vec![
            MathNode::Text(Arc::from("x")),
            MathNode::Text(Arc::from("+")),
            MathNode::Text(Arc::from("y")),
        ]);
        let output = render_mathml(&ast).expect("render_mathml must succeed for x + y");
        assert!(
            output.contains(r#"<math xmlns="http://www.w3.org/1998/Math/MathML""#),
            "MathML must include xmlns declaration; got: {output}"
        );
        assert!(
            output.contains("<mi>x</mi>"),
            "MathML must contain <mi>x</mi>; got: {output}"
        );
        assert!(
            output.contains("<mi>y</mi>"),
            "MathML must contain <mi>y</mi>; got: {output}"
        );
        assert!(
            output.contains("<mo>+</mo>"),
            "MathML must contain <mo>+</mo>; got: {output}"
        );
    }

    /// `render_mathml` for `$x^2$` produces `<msup><mi>x</mi><mn>2</mn></msup>`.
    ///
    /// RED GATE: fails until `render_mathml` is implemented.
    #[test]
    fn test_bc_1_10_003_mathml_superscript() {
        let ast = inline_ast(vec![MathNode::Superscript {
            base: Box::new(MathNode::Text(Arc::from("x"))),
            sup: Box::new(MathNode::Text(Arc::from("2"))),
        }]);
        let output = render_mathml(&ast).expect("render_mathml must succeed for x^2");
        assert!(
            output.contains("<msup>"),
            "MathML for x^2 must contain <msup>; got: {output}"
        );
        assert!(
            output.contains("<mi>x</mi>"),
            "MathML for x^2 must contain <mi>x</mi>; got: {output}"
        );
        assert!(
            output.contains("<mn>2</mn>"),
            "MathML for x^2 must contain <mn>2</mn>; got: {output}"
        );
    }

    /// `render_mathml` for `$x_2$` (subscript) produces `<msub>` element.
    ///
    /// RED GATE: fails until `render_mathml` is implemented.
    #[test]
    fn test_bc_1_10_003_mathml_subscript() {
        let ast = inline_ast(vec![MathNode::Subscript {
            base: Box::new(MathNode::Text(Arc::from("x"))),
            sub: Box::new(MathNode::Text(Arc::from("2"))),
        }]);
        let output = render_mathml(&ast).expect("render_mathml must succeed for x_2");
        assert!(
            output.contains("<msub>"),
            "MathML for x_2 must contain <msub>; got: {output}"
        );
    }

    /// `render_mathml` for `$\frac{1}{2}$` produces `<mfrac>` element.
    ///
    /// RED GATE: fails until `render_mathml` is implemented.
    #[test]
    fn test_bc_1_10_003_mathml_fraction() {
        let ast = inline_ast(vec![MathNode::Fraction {
            num: Box::new(MathNode::Text(Arc::from("1"))),
            denom: Box::new(MathNode::Text(Arc::from("2"))),
        }]);
        let output = render_mathml(&ast).expect("render_mathml must succeed for \\frac{1}{2}");
        assert!(
            output.contains("<mfrac>"),
            "MathML for \\frac must contain <mfrac>; got: {output}"
        );
    }

    /// Inline math produces root `<math display="inline"` attribute.
    ///
    /// RED GATE: fails until `render_mathml` is implemented.
    #[test]
    fn test_bc_1_10_003_mathml_inline_uses_display_inline() {
        let ast = inline_ast(vec![MathNode::Text(Arc::from("x"))]);
        let output = render_mathml(&ast).expect("render_mathml must succeed");
        assert!(
            output.contains(r#"display="inline""#),
            "inline MathML must have display=\"inline\"; got: {output}"
        );
        assert!(
            !output.contains(r#"display="block""#),
            "inline MathML must NOT have display=\"block\"; got: {output}"
        );
    }

    /// Display math (`$$...$$`) produces root `<math display="block"` attribute.
    ///
    /// RED GATE: fails until `render_mathml` is implemented.
    #[test]
    fn test_bc_1_10_003_mathml_display_uses_display_block() {
        let ast = display_ast(vec![MathNode::Text(Arc::from("x"))]);
        let output = render_mathml(&ast).expect("render_mathml must succeed");
        assert!(
            output.contains(r#"display="block""#),
            "display MathML must have display=\"block\"; got: {output}"
        );
        assert!(
            !output.contains(r#"display="inline""#),
            "display MathML must NOT have display=\"inline\"; got: {output}"
        );
    }

    /// `render_mathml` output for any expression contains a non-empty `aria-label`.
    ///
    /// RED GATE: fails until `render_mathml` is implemented.
    #[test]
    fn test_bc_1_10_003_mathml_has_aria_label() {
        let ast = inline_ast(vec![MathNode::Text(Arc::from("x"))]);
        let output = render_mathml(&ast).expect("render_mathml must succeed");
        assert!(
            output.contains("aria-label="),
            "MathML must include aria-label attribute; got: {output}"
        );
        // The aria-label value must be non-empty — not aria-label=""
        assert!(
            !output.contains(r#"aria-label="""#),
            "aria-label must not be empty; got: {output}"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // BC-1.10.003 — AC-002: MathML is accessible to screen readers
    // ─────────────────────────────────────────────────────────────────────────

    /// `ast_to_aria_label` for `$E = mc^2$` returns a label containing
    /// "equals" and "squared" (semantic plain-text description).
    ///
    /// RED GATE: fails until `ast_to_aria_label` is implemented.
    #[test]
    fn test_bc_1_10_003_aria_label_for_pythagorean() {
        // AST for E = mc^2: nodes E, =, m, c^2
        let ast = inline_ast(vec![
            MathNode::Text(Arc::from("E")),
            MathNode::Text(Arc::from("=")),
            MathNode::Text(Arc::from("m")),
            MathNode::Superscript {
                base: Box::new(MathNode::Text(Arc::from("c"))),
                sup: Box::new(MathNode::Text(Arc::from("2"))),
            },
        ]);
        let label = ast_to_aria_label(&ast);
        let lower = label.to_lowercase();
        assert!(
            lower.contains("equals"),
            "aria-label for E=mc^2 must contain 'equals'; got: {label}"
        );
        assert!(
            lower.contains("squared"),
            "aria-label for E=mc^2 must contain 'squared'; got: {label}"
        );
    }

    /// `ast_to_aria_label` for `$x + y$` returns a label containing "plus".
    ///
    /// RED GATE: fails until `ast_to_aria_label` is implemented.
    #[test]
    fn test_bc_1_10_003_aria_label_for_simple_sum() {
        let ast = inline_ast(vec![
            MathNode::Text(Arc::from("x")),
            MathNode::Text(Arc::from("+")),
            MathNode::Text(Arc::from("y")),
        ]);
        let label = ast_to_aria_label(&ast);
        let lower = label.to_lowercase();
        assert!(
            lower.contains("plus"),
            "aria-label for x+y must contain 'plus'; got: {label}"
        );
    }

    /// `ast_to_aria_label` returns a non-empty string for any non-empty AST.
    ///
    /// RED GATE: fails until `ast_to_aria_label` is implemented.
    #[test]
    fn test_bc_1_10_003_aria_label_non_empty_for_non_empty_ast() {
        let ast = inline_ast(vec![MathNode::Text(Arc::from("x"))]);
        let label = ast_to_aria_label(&ast);
        assert!(
            !label.is_empty(),
            "aria-label must not be empty for a non-empty AST"
        );
    }

    /// `ast_to_aria_label` for an empty AST returns a non-empty fallback string.
    ///
    /// Finding I4: empty AST must NOT produce `aria-label=""` — screen readers
    /// announce empty attributes awkwardly.  The fallback is "empty math
    /// expression".
    ///
    /// RED GATE: fails until `ast_to_aria_label` is implemented.
    #[test]
    fn test_bc_1_10_003_aria_label_empty_ast_returns_fallback() {
        let ast = inline_ast(vec![]);
        let label = ast_to_aria_label(&ast);
        assert!(
            !label.is_empty(),
            "aria-label for empty AST must not be empty string; got: {label}"
        );
        assert_eq!(
            label, "empty math expression",
            "aria-label for empty AST must be 'empty math expression'; got: {label}"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Finding I1 — aria-label "times" between adjacent identifiers
    // Finding I4 — empty AST fallback label
    // ─────────────────────────────────────────────────────────────────────────

    /// `ast_to_aria_label` for `$E = mc^2$` yields "E equals m times c squared".
    ///
    /// AC-002 mandates that adjacent single-letter identifiers are connected
    /// by "times" in the spoken label.
    #[test]
    fn test_i1_aria_label_times_between_adjacent_identifiers() {
        // AST for E = mc^2: nodes E, =, m, c^2
        let ast = inline_ast(vec![
            MathNode::Text(Arc::from("E")),
            MathNode::Text(Arc::from("=")),
            MathNode::Text(Arc::from("m")),
            MathNode::Superscript {
                base: Box::new(MathNode::Text(Arc::from("c"))),
                sup: Box::new(MathNode::Text(Arc::from("2"))),
            },
        ]);
        let label = ast_to_aria_label(&ast);
        assert_eq!(
            label, "E equals m times c squared",
            "aria-label for E=mc^2 must be 'E equals m times c squared'; got: {label}"
        );
    }

    /// `ast_to_aria_label` for `$x + y$` does NOT insert "times" (an operator
    /// already separates the identifiers).
    #[test]
    fn test_i1_aria_label_no_times_when_operator_separates() {
        let ast = inline_ast(vec![
            MathNode::Text(Arc::from("x")),
            MathNode::Text(Arc::from("+")),
            MathNode::Text(Arc::from("y")),
        ]);
        let label = ast_to_aria_label(&ast);
        // "+" becomes "plus", so no "times" should appear
        assert!(
            !label.contains("times"),
            "aria-label for x+y must not contain 'times'; got: {label}"
        );
        assert!(
            label.contains("plus"),
            "aria-label for x+y must contain 'plus'; got: {label}"
        );
    }

    /// `ast_to_aria_label` for an empty AST returns the fallback "empty math expression".
    ///
    /// Finding I4: must never produce `aria-label=""`.
    #[test]
    fn test_i4_aria_label_empty_ast_returns_fallback_string() {
        let ast = inline_ast(vec![]);
        let label = ast_to_aria_label(&ast);
        assert_eq!(
            label, "empty math expression",
            "empty AST must yield 'empty math expression'; got: {label}"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // BC-1.10.003 — Well-formedness and element constraints
    // ─────────────────────────────────────────────────────────────────────────

    /// `render_mathml` output is well-formed XML (all tags balance).
    ///
    /// Uses `quick-xml` event walk to confirm no unclosed tags.
    ///
    /// RED GATE: fails until `render_mathml` is implemented.
    #[test]
    fn test_bc_1_10_003_mathml_xml_is_wellformed() {
        let ast = inline_ast(vec![
            MathNode::Text(Arc::from("x")),
            MathNode::Superscript {
                base: Box::new(MathNode::Text(Arc::from("y"))),
                sup: Box::new(MathNode::Text(Arc::from("2"))),
            },
        ]);
        let output = render_mathml(&ast).expect("render_mathml must succeed");
        assert_wellformed_xml(&output)
            .unwrap_or_else(|e| panic!("MathML output is not well-formed XML: {e}"));
    }

    /// `render_mathml` output uses only `MathML` elements — no HTML tags.
    ///
    /// Checks that forbidden HTML elements (div, span, p, h1-h6) are absent.
    ///
    /// RED GATE: fails until `render_mathml` is implemented.
    #[test]
    fn test_bc_1_10_003_mathml_no_html_elements() {
        let ast = inline_ast(vec![MathNode::Text(Arc::from("x"))]);
        let output = render_mathml(&ast).expect("render_mathml must succeed");
        for tag in &["<div", "<span", "<p>", "<p ", "<h1", "<h2", "<table"] {
            assert!(
                !output.contains(tag),
                "MathML must not contain HTML element {tag}; got: {output}"
            );
        }
    }

    /// `render_mathml` namespace declaration is exactly the W3C `MathML` URI.
    ///
    /// RED GATE: fails until `render_mathml` is implemented.
    #[test]
    fn test_bc_1_10_003_mathml_namespace_is_w3c_uri() {
        let ast = inline_ast(vec![MathNode::Text(Arc::from("x"))]);
        let output = render_mathml(&ast).expect("render_mathml must succeed");
        assert!(
            output.contains("http://www.w3.org/1998/Math/MathML"),
            "MathML namespace must be 'http://www.w3.org/1998/Math/MathML'; got: {output}"
        );
    }

    /// `render_mathml` for `$\frac{1}{2}$` produces well-formed XML with `<mfrac>`.
    ///
    /// RED GATE: fails until `render_mathml` is implemented.
    #[test]
    fn test_bc_1_10_003_mathml_fraction_wellformed() {
        let ast = inline_ast(vec![MathNode::Fraction {
            num: Box::new(MathNode::Text(Arc::from("1"))),
            denom: Box::new(MathNode::Text(Arc::from("2"))),
        }]);
        let output = render_mathml(&ast).expect("render_mathml must succeed for fraction");
        assert!(output.contains("<mfrac>"), "must contain <mfrac>");
        assert_wellformed_xml(&output)
            .unwrap_or_else(|e| panic!("fraction MathML is not well-formed: {e}"));
    }

    /// `render_mathml` for a `Sqrt` node produces `<msqrt>` or `<mroot>` element.
    ///
    /// RED GATE: fails until `render_mathml` is implemented.
    #[test]
    fn test_bc_1_10_003_mathml_sqrt_element() {
        let ast = inline_ast(vec![MathNode::Sqrt {
            index: None,
            radicand: Box::new(MathNode::Text(Arc::from("x"))),
        }]);
        let output = render_mathml(&ast).expect("render_mathml must succeed for sqrt");
        assert!(
            output.contains("<msqrt>") || output.contains("<mroot>"),
            "MathML for \\sqrt must contain <msqrt> or <mroot>; got: {output}"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // BC-1.10.003 — EC-001: Display math in MathML → display="block"
    // ─────────────────────────────────────────────────────────────────────────

    /// EC-001: Display math in `MathML` gets `display="block"` on root `<math>`.
    ///
    /// RED GATE: fails until `render_mathml` is implemented.
    #[test]
    fn test_bc_1_10_003_ec001_display_math_gets_block_attribute() {
        let ast = display_ast(vec![MathNode::Operator(Arc::from("sum"))]);
        let output = render_mathml(&ast).expect("render_mathml must succeed for display math");
        // Root <math> element must carry display="block"
        let root_end = output.find('>').expect("output must contain a '>'");
        let root_open = &output[..=root_end];
        assert!(
            root_open.contains(r#"display="block""#),
            "root <math> of display mode must have display=\"block\" before first '>'; got root: {root_open}"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // BC-1.10.003 — AC-004: Single MathAst source (no re-parsing)
    // ─────────────────────────────────────────────────────────────────────────

    /// The same [`MathAst`] can be passed to `render_mathml` twice without error.
    ///
    /// This exercises AC-004: `render_mathml` takes `&MathAst` (shared reference).
    ///
    /// RED GATE: fails until `render_mathml` is implemented.
    #[test]
    fn test_bc_1_10_003_mathml_ast_reusable_across_calls() {
        let ast = inline_ast(vec![MathNode::Text(Arc::from("x"))]);
        // Both calls take &ast — same AST, no re-parsing
        let first = render_mathml(&ast).expect("first call must succeed");
        let second = render_mathml(&ast).expect("second call must succeed");
        assert_eq!(
            first, second,
            "render_mathml must be deterministic for the same AST"
        );
    }
}
