//! Document section collection — assembles [`GeneratedSection`] data for DOCX
//! and PDF output from the semantic [`slideforge_types::Deck`] IR.
//!
//! This module implements the layout stage's responsibility under SS-05: after
//! the evaluator has resolved all `{{ expr }}` and `@data` bindings, the
//! section collection pass walks the `Deck` and produces a
//! `Vec<GeneratedSection>` that is stored on [`crate::types::LaidOutDeck`].
//!
//! ## Architecture (DI-008 / DI-012)
//!
//! - **Pure collection only.** No Word XML generation happens here. DOCX/PDF
//!   rendering is delegated to `SectionType` plugin implementations
//!   (STORY-041/042).
//! - **Single source for all document formats.** Both DOCX and PDF exporters
//!   consume `LaidOutDeck.sections`. No format-specific branching occurs in
//!   the layout stage.
//! - **Exporter filtering by `target_formats`.** `GeneratedSection` carries a
//!   `target_formats` bitset (AC-005). PPTX and HTML exporters filter out
//!   sections where their format is not listed.
//!
//! ## Auto-generated sections (BC-3.02.001)
//!
//! | Source | Produced section |
//! |--------|-----------------|
//! | Slides with `takeaway:` field | [`SectionKind::ExecutiveSummary`] |
//! | `severity_cards` slides | [`SectionKind::RiskRegister`] |
//!
//! ## Manually authored sections (BC-3.02.002)
//!
//! `section <type>:` blocks in the `Deck` IR are collected into
//! [`SectionSource::ManuallyAuthored`] entries. An unrecognised section type
//! returns [`crate::error::LayoutError::UnknownSectionType`].

use std::sync::Arc;

use slideforge_types::{Deck, OrderedMap, Value};

/// The output format a section should be included in.
///
/// `OutputFormat` is used in [`GeneratedSection::target_formats`] to signal
/// which exporters should render a section. PPTX and HTML exporters skip
/// sections where their format is absent from this list.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OutputFormat {
    /// DOCX (Word) export.
    Docx,
    /// PDF export.
    Pdf,
    /// PPTX (`PowerPoint`) export.
    Pptx,
    /// HTML export.
    Html,
    /// Web preview export.
    Preview,
}

/// The kind of a generated document section.
///
/// `SectionKind` identifies the semantics of a section and controls how a
/// `SectionType` plugin renders it. Auto-generated sections have a fixed
/// semantic kind; manually authored sections carry their type name as a
/// `ManualSection` variant.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SectionKind {
    /// An auto-generated executive summary built from slide `takeaway:` fields.
    ///
    /// Heading: `"Executive Summary"`. Items: one
    /// [`SectionItem::TakeawayBullet`] per contributing slide, in slide order.
    ExecutiveSummary,

    /// An auto-generated risk register built from `severity_cards` slides.
    ///
    /// Heading: `"Risk Register"`. Items: one [`SectionItem::RiskRow`] per
    /// card entry, in slide order. No de-duplication is applied (BC-3.02.001
    /// EC-003).
    RiskRegister,

    /// A manually authored section block from `section <type>:` DSL syntax.
    ///
    /// Supported types: `methodology`, `scope`, `approval`, `appendix`,
    /// `glossary`. The type name is stored here for plugin dispatch.
    ManualSection(Arc<str>),
}

/// Whether a section was auto-generated from slide data or manually authored.
///
/// This distinction is preserved in the layout IR so that:
/// - The supersession rule (AC-006) can suppress auto-generated sections when a
///   manual section of the same kind is present.
/// - The DOCX/PDF exporters can apply different rendering policies per source.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SectionSource {
    /// Assembled by the layout engine from slide field data.
    AutoGenerated,
    /// Parsed from an explicit `section <type>:` block in the `.sf` source.
    ManuallyAuthored,
}

/// A single item within a [`GeneratedSection`].
///
/// The variant determines what a `SectionType` plugin renders:
/// - [`SectionItem::TakeawayBullet`] renders as a bullet point in an executive
///   summary.
/// - [`SectionItem::RiskRow`] renders as a table row in a risk register.
/// - [`SectionItem::Custom`] is a catch-all for manually authored section
///   content with arbitrary key-value data.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SectionItem {
    /// A single bullet derived from a slide's `takeaway:` field.
    TakeawayBullet(Arc<str>),

    /// A risk entry derived from a `severity_cards` slide.
    RiskRow {
        /// The risk item title.
        title: Arc<str>,
        /// Severity level (e.g., `"High"`, `"Medium"`, `"Low"`).
        severity: Arc<str>,
        /// Human-readable description of the risk.
        description: Arc<str>,
        /// The risk owner (name or role).
        owner: Arc<str>,
    },

    /// A custom section item from a manually authored `section:` block.
    ///
    /// The map keys are field names declared in the section block; values are
    /// the resolved [`slideforge_types::Value`]s.
    ///
    /// Uses [`OrderedMap`] (not `BTreeMap`) to preserve insertion order and
    /// satisfy the `Hash` requirement on all layout IR types (AC-010).
    Custom(OrderedMap<Arc<str>, Value>),
}

/// A collected document section ready for exporter consumption.
///
/// `GeneratedSection` is the primary output of this module and is stored as a
/// `Vec<GeneratedSection>` on [`crate::types::LaidOutDeck`].
///
/// ## Ordering
///
/// Within `LaidOutDeck.sections`, sections appear in the order determined by
/// [`collect_sections`]:
/// 1. Manually authored sections first (in DSL source order).
/// 2. Auto-generated sections after (in default kind order: executive summary
///    before risk register).
///
/// If `section_order:` is declared in the deck metadata, [`collect_sections`]
/// sorts the sections accordingly (AC-007).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct GeneratedSection {
    /// The semantic kind of this section.
    pub kind: SectionKind,

    /// Whether this section was auto-generated or manually authored.
    pub source: SectionSource,

    /// The ordered list of items in this section.
    pub items: Vec<SectionItem>,

    /// The section heading text.
    ///
    /// For auto-generated sections this is a canonical default
    /// (`"Executive Summary"`, `"Risk Register"`). For manually authored
    /// sections this is the heading declared in the `section:` block, or the
    /// default for that section type if none was declared.
    pub heading: Arc<str>,

    /// The output formats that should render this section.
    ///
    /// Set by the layout stage so that exporters can filter without
    /// re-examining section kind. Default for most sections: `[Docx, Pdf]`.
    /// PPTX and HTML exporters skip sections where their format is absent
    /// (AC-005).
    pub target_formats: Vec<OutputFormat>,
}

/// Collect all document sections from a fully evaluated [`Deck`].
///
/// `collect_sections` is the main entry point called by [`crate::layout::run`].
/// It applies the supersession rule (AC-006): if both a manual and an
/// auto-generated section of the same kind are present, the manual section is
/// retained and the auto-generated one is suppressed.
///
/// The returned `Vec<GeneratedSection>` is stored in
/// [`crate::types::LaidOutDeck::sections`]. Ordering follows AC-007:
/// manual sections first (in DSL source order), then auto-generated sections
/// (executive summary before risk register), unless `section_order:` in the
/// deck metadata overrides this.
///
/// # Errors
///
/// Returns [`crate::error::LayoutError::UnknownSectionType`] if the deck
/// contains a manually authored `section <type>:` block with an unrecognised
/// type name.
///
/// # Panics
///
/// Does not panic. All error paths return `Err`.
#[must_use]
pub fn collect_sections(deck: &Deck) -> Vec<GeneratedSection> {
    // Manual sections (from section_blocks in the Deck) are collected first.
    // NOTE: `slideforge_types::Deck` does not yet expose a `section_blocks` field
    // (that field will be added when the parser/evaluator pipeline is implemented).
    // For now, manual_sections is always empty; the auto-generated collection below
    // is the only active path. When Deck gains `section_blocks`, the manual collection
    // logic here should be extended to iterate that field and convert each block
    // into a GeneratedSection with SectionSource::ManuallyAuthored.
    let manual_sections: Vec<GeneratedSection> = Vec::new();

    // Build a set of manually-authored section kinds so auto-generated sections
    // of the same kind can be suppressed (supersession rule, AC-006).
    let manual_kinds: std::collections::HashSet<&SectionKind> =
        manual_sections.iter().map(|s| &s.kind).collect();

    // Collect auto-generated sections.
    let mut auto_sections: Vec<GeneratedSection> = Vec::new();

    // ExecutiveSummary from takeaway fields — suppressed if a manual section of the same
    // kind is present (AC-006).
    if !manual_kinds.contains(&SectionKind::ExecutiveSummary)
        && let Some(exec_summary) = collect_executive_summary(deck)
    {
        auto_sections.push(exec_summary);
    }

    // RiskRegister from severity_cards slides — suppressed if a manual section of the same
    // kind is present (AC-006).
    if !manual_kinds.contains(&SectionKind::RiskRegister)
        && let Some(risk_register) = collect_risk_register(deck)
    {
        auto_sections.push(risk_register);
    }

    // Final ordering: manual sections first (AC-007), then auto-generated.
    let mut result = manual_sections;
    result.extend(auto_sections);
    result
}

/// Collect the auto-generated `executive_summary` section from slide `takeaway:` fields.
///
/// Walks `deck.slides` in order; for each slide that has a `takeaway:` field
/// resolving to a plain string, appends a [`SectionItem::TakeawayBullet`] to
/// the result.
///
/// Returns `None` if no slides contribute a takeaway (AC-003).
///
/// # Contract
///
/// - Slide order is preserved (BC-3.02.001 postcondition 2).
/// - Only `FieldValue::Literal(Value::Str(_))` takeaway values are collected;
///   unresolved `FieldValue::Expr` or `FieldValue::Interpolated` values are
///   silently skipped (those indicate an evaluator bug — the evaluator should
///   have resolved all expressions before layout runs).
#[must_use]
pub fn collect_executive_summary(deck: &Deck) -> Option<GeneratedSection> {
    use slideforge_types::FieldValue;
    use slideforge_types::Value;

    let items: Vec<SectionItem> = deck
        .slides
        .iter()
        .filter_map(|slide| match slide.fields.get("takeaway") {
            Some(FieldValue::Literal(Value::Str(s))) => {
                Some(SectionItem::TakeawayBullet(Arc::clone(s)))
            },
            _ => None,
        })
        .collect();

    if items.is_empty() {
        return None;
    }

    Some(GeneratedSection {
        kind: SectionKind::ExecutiveSummary,
        source: SectionSource::AutoGenerated,
        items,
        heading: Arc::from("Executive Summary"),
        target_formats: vec![OutputFormat::Docx, OutputFormat::Pdf],
    })
}

/// Collect the auto-generated `risk_register` section from `severity_cards` slides.
///
/// Walks `deck.slides` in order; for each slide with `slide_type == "severity_cards"`,
/// reads its card data and produces one [`SectionItem::RiskRow`] per card entry
/// (title, severity, description, owner fields).
///
/// Returns `None` if no `severity_cards` slides exist in the deck (AC-003).
///
/// # Contract
///
/// - Multiple `severity_cards` slides each contribute rows to the same section
///   (BC-3.02.001 postcondition 3).
/// - No de-duplication is applied — duplicate rows from an `@for` loop are all
///   included (BC-3.02.001 EC-003).
/// - If `@if` suppresses all `severity_cards` slides, this function returns
///   `None` (BC-3.02.001 EC-004).
#[must_use]
pub fn collect_risk_register(deck: &Deck) -> Option<GeneratedSection> {
    use slideforge_types::FieldValue;
    use slideforge_types::Value;

    /// Extract a string value from a slide field, returning an empty `Arc<str>` if absent.
    fn extract_str(slide: &slideforge_types::Slide, field: &str) -> Arc<str> {
        match slide.fields.get(field) {
            Some(FieldValue::Literal(Value::Str(s))) => Arc::clone(s),
            _ => Arc::from(""),
        }
    }

    let items: Vec<SectionItem> = deck
        .slides
        .iter()
        .filter(|slide| slide.slide_type.as_ref() == "severity_cards")
        .map(|slide| SectionItem::RiskRow {
            title: extract_str(slide, "title"),
            severity: extract_str(slide, "severity"),
            description: extract_str(slide, "description"),
            owner: extract_str(slide, "owner"),
        })
        .collect();

    if items.is_empty() {
        return None;
    }

    Some(GeneratedSection {
        kind: SectionKind::RiskRegister,
        source: SectionSource::AutoGenerated,
        items,
        heading: Arc::from("Risk Register"),
        target_formats: vec![OutputFormat::Docx, OutputFormat::Pdf],
    })
}

#[cfg(test)]
#[allow(
    clippy::missing_docs_in_private_items,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::doc_markdown
)]
mod tests {
    use std::sync::Arc;

    use slideforge_types::{Deck, DeckMetadata, FieldValue, OrderedMap, Slide, SourceSpan, Value};

    use super::*;

    // ─────────────────────────────────────────────────────────────────────────
    // Test helpers
    // ─────────────────────────────────────────────────────────────────────────

    fn make_metadata() -> DeckMetadata {
        DeckMetadata {
            title: Some(Arc::from("Test Deck")),
            slideforge_version: Arc::from("0.1.0"),
            lang: Some(Arc::from("en-US")),
            author: None,
        }
    }

    fn make_deck(slides: Vec<Slide>) -> Deck {
        Deck {
            slides,
            vars: OrderedMap::new(),
            metadata: make_metadata(),
            registers: OrderedMap::new(),
        }
    }

    fn make_slide(slide_type: &str) -> Slide {
        Slide {
            slide_type: Arc::from(slide_type),
            fields: OrderedMap::new(),
            blocks: vec![],
            register: None,
            tags: vec![],
            source_span: SourceSpan::default(),
        }
    }

    fn make_slide_with_takeaway(slide_type: &str, takeaway: &str) -> Slide {
        let mut fields = OrderedMap::new();
        fields.insert(
            Arc::from("takeaway"),
            FieldValue::Literal(Value::Str(Arc::from(takeaway))),
        );
        Slide {
            slide_type: Arc::from(slide_type),
            fields,
            blocks: vec![],
            register: None,
            tags: vec![],
            source_span: SourceSpan::default(),
        }
    }

    fn make_severity_card_slide(
        title: &str,
        severity: &str,
        description: &str,
        owner: &str,
    ) -> Slide {
        let mut fields = OrderedMap::new();
        fields.insert(
            Arc::from("title"),
            FieldValue::Literal(Value::Str(Arc::from(title))),
        );
        fields.insert(
            Arc::from("severity"),
            FieldValue::Literal(Value::Str(Arc::from(severity))),
        );
        fields.insert(
            Arc::from("description"),
            FieldValue::Literal(Value::Str(Arc::from(description))),
        );
        fields.insert(
            Arc::from("owner"),
            FieldValue::Literal(Value::Str(Arc::from(owner))),
        );
        Slide {
            slide_type: Arc::from("severity_cards"),
            fields,
            blocks: vec![],
            register: None,
            tags: vec![],
            source_span: SourceSpan::default(),
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // BC-3.02.001 / AC-001 — executive_summary from takeaway fields
    // ─────────────────────────────────────────────────────────────────────────

    /// AC-001 — deck with 3 takeaway slides produces executive_summary with 3
    /// items in slide order.
    ///
    /// FAILS at Red Gate: collect_executive_summary returns todo!().
    #[test]
    fn test_bc_3_02_001_executive_summary_three_takeaways() {
        let deck = make_deck(vec![
            make_slide_with_takeaway("content", "Takeaway from slide 1"),
            make_slide("blank"),
            make_slide_with_takeaway("bullets", "Takeaway from slide 3"),
            make_slide_with_takeaway("quote", "Takeaway from slide 4"),
        ]);
        let section = collect_executive_summary(&deck)
            .expect("deck with takeaway slides must produce an executive_summary section");
        assert_eq!(
            section.kind,
            SectionKind::ExecutiveSummary,
            "section kind must be ExecutiveSummary"
        );
        assert_eq!(
            section.source,
            SectionSource::AutoGenerated,
            "auto-collected section must have source AutoGenerated"
        );
        assert_eq!(
            section.items.len(),
            3,
            "must collect exactly 3 TakeawayBullet items (slide without takeaway is skipped)"
        );
        assert_eq!(
            section.items[0],
            SectionItem::TakeawayBullet(Arc::from("Takeaway from slide 1")),
        );
        assert_eq!(
            section.items[1],
            SectionItem::TakeawayBullet(Arc::from("Takeaway from slide 3")),
        );
        assert_eq!(
            section.items[2],
            SectionItem::TakeawayBullet(Arc::from("Takeaway from slide 4")),
        );
    }

    /// AC-001 — heading must be "Executive Summary".
    ///
    /// FAILS at Red Gate: collect_executive_summary returns todo!().
    #[test]
    fn test_bc_3_02_001_executive_summary_heading() {
        let deck = make_deck(vec![make_slide_with_takeaway("content", "Key point")]);
        let section = collect_executive_summary(&deck).expect("must produce section");
        assert_eq!(
            section.heading.as_ref(),
            "Executive Summary",
            "heading must be exactly 'Executive Summary'"
        );
    }

    /// AC-001 — target_formats must include Docx and Pdf.
    ///
    /// FAILS at Red Gate: collect_executive_summary returns todo!().
    #[test]
    fn test_bc_3_02_001_executive_summary_target_formats() {
        let deck = make_deck(vec![make_slide_with_takeaway("content", "Key point")]);
        let section = collect_executive_summary(&deck).expect("must produce section");
        assert!(
            section.target_formats.contains(&OutputFormat::Docx),
            "executive_summary must target Docx"
        );
        assert!(
            section.target_formats.contains(&OutputFormat::Pdf),
            "executive_summary must target Pdf"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // BC-3.02.001 / AC-003 — section omitted when no contributing slides
    // ─────────────────────────────────────────────────────────────────────────

    /// EC-001 / AC-003 — deck with no takeaway fields produces no executive_summary.
    ///
    /// FAILS at Red Gate: collect_executive_summary returns todo!().
    #[test]
    fn test_bc_3_02_001_executive_summary_absent_when_no_takeaways() {
        let deck = make_deck(vec![
            make_slide("title"),
            make_slide("content"),
            make_slide("blank"),
        ]);
        let result = collect_executive_summary(&deck);
        assert!(
            result.is_none(),
            "collect_executive_summary must return None when no slides have a takeaway field"
        );
    }

    /// AC-003 — empty deck produces no executive_summary.
    ///
    /// FAILS at Red Gate: collect_executive_summary returns todo!().
    #[test]
    fn test_bc_3_02_001_executive_summary_absent_for_empty_deck() {
        let deck = make_deck(vec![]);
        let result = collect_executive_summary(&deck);
        assert!(
            result.is_none(),
            "collect_executive_summary must return None for a deck with no slides"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // BC-3.02.001 / AC-002 — risk_register from severity_cards slides
    // ─────────────────────────────────────────────────────────────────────────

    /// AC-002 — deck with severity_cards slides produces a risk_register section.
    ///
    /// FAILS at Red Gate: collect_risk_register returns todo!().
    #[test]
    fn test_bc_3_02_001_risk_register_from_severity_cards() {
        let deck = make_deck(vec![
            make_slide("title"),
            make_severity_card_slide("Budget Risk", "High", "May exceed by 20%", "CFO"),
            make_severity_card_slide("Timeline Risk", "Medium", "Delay possible in Q3", "PM"),
        ]);
        let section = collect_risk_register(&deck)
            .expect("deck with severity_cards slides must produce a risk_register section");
        assert_eq!(
            section.kind,
            SectionKind::RiskRegister,
            "section kind must be RiskRegister"
        );
        assert_eq!(
            section.source,
            SectionSource::AutoGenerated,
            "auto-collected section must have source AutoGenerated"
        );
        assert_eq!(
            section.items.len(),
            2,
            "must collect exactly 2 RiskRow items"
        );
        assert_eq!(
            section.items[0],
            SectionItem::RiskRow {
                title: Arc::from("Budget Risk"),
                severity: Arc::from("High"),
                description: Arc::from("May exceed by 20%"),
                owner: Arc::from("CFO"),
            }
        );
    }

    /// AC-002 — heading for risk_register must be "Risk Register".
    ///
    /// FAILS at Red Gate: collect_risk_register returns todo!().
    #[test]
    fn test_bc_3_02_001_risk_register_heading() {
        let deck = make_deck(vec![make_severity_card_slide(
            "Risk A",
            "Low",
            "Minor issue",
            "Team Lead",
        )]);
        let section = collect_risk_register(&deck).expect("must produce section");
        assert_eq!(
            section.heading.as_ref(),
            "Risk Register",
            "heading must be exactly 'Risk Register'"
        );
    }

    /// AC-003 — deck with no severity_cards slides produces no risk_register.
    ///
    /// FAILS at Red Gate: collect_risk_register returns todo!().
    #[test]
    fn test_bc_3_02_001_risk_register_absent_when_no_severity_cards() {
        let deck = make_deck(vec![make_slide("title"), make_slide("content")]);
        let result = collect_risk_register(&deck);
        assert!(
            result.is_none(),
            "collect_risk_register must return None when no severity_cards slides exist"
        );
    }

    /// EC-003 — multiple severity_cards slides produce rows in a single section, no dedup.
    ///
    /// FAILS at Red Gate: collect_risk_register returns todo!().
    #[test]
    fn test_bc_3_02_001_risk_register_multiple_slides_no_dedup() {
        // Two slides with identical risk data — both rows must appear.
        let deck = make_deck(vec![
            make_severity_card_slide("Same Risk", "High", "Repeated", "Owner"),
            make_severity_card_slide("Same Risk", "High", "Repeated", "Owner"),
        ]);
        let section = collect_risk_register(&deck).expect("must produce section");
        assert_eq!(
            section.items.len(),
            2,
            "risk rows must not be de-duplicated (EC-003)"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Type structure tests — SectionKind, SectionSource, SectionItem, GeneratedSection
    // ─────────────────────────────────────────────────────────────────────────

    /// All SectionKind variants exist and are pattern-matchable.
    #[test]
    fn test_bc_3_02_001_section_kind_variants_exist() {
        let exec = SectionKind::ExecutiveSummary;
        let risk = SectionKind::RiskRegister;
        let manual = SectionKind::ManualSection(Arc::from("methodology"));
        assert!(matches!(exec, SectionKind::ExecutiveSummary));
        assert!(matches!(risk, SectionKind::RiskRegister));
        assert!(matches!(manual, SectionKind::ManualSection(_)));
    }

    /// SectionSource variants exist.
    #[test]
    fn test_bc_3_02_001_section_source_variants_exist() {
        let auto = SectionSource::AutoGenerated;
        let manual = SectionSource::ManuallyAuthored;
        assert!(matches!(auto, SectionSource::AutoGenerated));
        assert!(matches!(manual, SectionSource::ManuallyAuthored));
    }

    /// SectionItem variants exist with expected fields.
    #[test]
    fn test_bc_3_02_001_section_item_variants_exist() {
        let bullet = SectionItem::TakeawayBullet(Arc::from("Key insight"));
        let row = SectionItem::RiskRow {
            title: Arc::from("Risk A"),
            severity: Arc::from("High"),
            description: Arc::from("Description"),
            owner: Arc::from("Owner"),
        };
        let custom = SectionItem::Custom(OrderedMap::new());
        assert!(matches!(bullet, SectionItem::TakeawayBullet(_)));
        assert!(matches!(row, SectionItem::RiskRow { .. }));
        assert!(matches!(custom, SectionItem::Custom(_)));
    }

    /// OutputFormat variants exist.
    #[test]
    fn test_bc_3_02_001_output_format_variants_exist() {
        let docx = OutputFormat::Docx;
        let pdf = OutputFormat::Pdf;
        let pptx = OutputFormat::Pptx;
        let html = OutputFormat::Html;
        let preview = OutputFormat::Preview;
        assert!(matches!(docx, OutputFormat::Docx));
        assert!(matches!(pdf, OutputFormat::Pdf));
        assert!(matches!(pptx, OutputFormat::Pptx));
        assert!(matches!(html, OutputFormat::Html));
        assert!(matches!(preview, OutputFormat::Preview));
    }

    /// GeneratedSection implements Hash + Eq + Clone (AC-010).
    #[test]
    fn test_bc_3_02_001_generated_section_implements_hash_eq_clone() {
        use std::collections::HashSet;

        let section = GeneratedSection {
            kind: SectionKind::ExecutiveSummary,
            source: SectionSource::AutoGenerated,
            items: vec![SectionItem::TakeawayBullet(Arc::from("Key point"))],
            heading: Arc::from("Executive Summary"),
            target_formats: vec![OutputFormat::Docx, OutputFormat::Pdf],
        };
        let section2 = section.clone();
        assert_eq!(section, section2);
        let mut set = HashSet::new();
        set.insert(section);
        assert_eq!(set.len(), 1);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // BC-3.02.001 / AC-001 — skips slides without takeaway (mixed deck)
    // ─────────────────────────────────────────────────────────────────────────

    /// AC-001 — deck with 5 slides where only slides 1 and 3 have a takeaway
    /// must produce a section with exactly 2 items in slide order (skipping
    /// slides 2, 4, 5 which have no takeaway field).
    ///
    /// Exercises BC-3.02.001 postcondition 2: "slides with no takeaway: field
    /// are not included; order matches source slide order".
    ///
    /// FAILS at Red Gate: collect_executive_summary returns todo!().
    #[test]
    fn test_bc_3_02_001_executive_summary_skips_slides_without_takeaway() {
        let deck = make_deck(vec![
            make_slide_with_takeaway("content", "First key point"),
            make_slide("title"),
            make_slide_with_takeaway("bullets", "Second key point"),
            make_slide("stat_callout"),
            make_slide("section_break"),
        ]);
        let section = collect_executive_summary(&deck)
            .expect("deck with 2 takeaway slides must produce an executive_summary section");
        assert_eq!(
            section.items.len(),
            2,
            "only slides with takeaway: fields contribute — 3 slides without takeaway must be skipped"
        );
        assert_eq!(
            section.items[0],
            SectionItem::TakeawayBullet(Arc::from("First key point")),
            "first item must come from slide 0 (index 0)"
        );
        assert_eq!(
            section.items[1],
            SectionItem::TakeawayBullet(Arc::from("Second key point")),
            "second item must come from slide 2 (index 2), not slide 1"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // BC-3.02.001 / AC-002 — RiskRow field preservation
    // ─────────────────────────────────────────────────────────────────────────

    /// AC-002 — each RiskRow preserves all four source card fields: title,
    /// severity, description, owner — with exact string equality.
    ///
    /// Exercises BC-3.02.001 postcondition 3 field-level contract: the row
    /// must carry the exact text from the card, no truncation or transformation.
    ///
    /// FAILS at Red Gate: collect_risk_register returns todo!().
    #[test]
    fn test_bc_3_02_001_risk_row_preserves_card_fields() {
        let deck = make_deck(vec![make_severity_card_slide(
            "Integration Failure",
            "Critical",
            "Third-party API may be deprecated in Q2",
            "Platform Lead",
        )]);
        let section = collect_risk_register(&deck).expect("must produce section");
        assert_eq!(
            section.items.len(),
            1,
            "one severity_cards slide must produce exactly one RiskRow"
        );
        match &section.items[0] {
            SectionItem::RiskRow {
                title,
                severity,
                description,
                owner,
            } => {
                assert_eq!(
                    title.as_ref(),
                    "Integration Failure",
                    "RiskRow title must match card title field exactly"
                );
                assert_eq!(
                    severity.as_ref(),
                    "Critical",
                    "RiskRow severity must match card severity field exactly"
                );
                assert_eq!(
                    description.as_ref(),
                    "Third-party API may be deprecated in Q2",
                    "RiskRow description must match card description field exactly"
                );
                assert_eq!(
                    owner.as_ref(),
                    "Platform Lead",
                    "RiskRow owner must match card owner field exactly"
                );
            },
            other => panic!("expected SectionItem::RiskRow, got {other:?}"),
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // BC-3.02.001 — collect_sections integration (combines auto-generated)
    // ─────────────────────────────────────────────────────────────────────────

    /// AC-001 + AC-002 + AC-007 — collect_sections on a deck with both takeaway
    /// slides and severity_cards slides returns a Vec containing both the
    /// ExecutiveSummary and RiskRegister sections.
    ///
    /// Per AC-007 default ordering: auto-generated sections appear in default
    /// kind order (ExecutiveSummary before RiskRegister).
    ///
    /// FAILS at Red Gate: collect_sections returns todo!().
    #[test]
    fn test_bc_3_02_001_collect_sections_combines_auto_generated() {
        let deck = make_deck(vec![
            make_slide_with_takeaway("content", "Strategic point"),
            make_severity_card_slide("Budget Overrun", "High", "10% over plan", "CFO"),
        ]);
        let sections = collect_sections(&deck);
        assert!(
            !sections.is_empty(),
            "collect_sections must return at least one section when both takeaway and severity_cards slides exist"
        );
        // Both ExecutiveSummary and RiskRegister must be present.
        let has_exec_summary = sections
            .iter()
            .any(|s| s.kind == SectionKind::ExecutiveSummary);
        let has_risk_register = sections.iter().any(|s| s.kind == SectionKind::RiskRegister);
        assert!(
            has_exec_summary,
            "collect_sections must include ExecutiveSummary section when takeaway slides exist"
        );
        assert!(
            has_risk_register,
            "collect_sections must include RiskRegister section when severity_cards slides exist"
        );
    }

    /// AC-003 / EC-001 — collect_sections on a deck with no takeaway fields
    /// and no severity_cards slides returns an empty Vec.
    ///
    /// FAILS at Red Gate: collect_sections returns todo!().
    #[test]
    fn test_bc_3_02_001_collect_sections_empty_when_no_contributing_slides() {
        let deck = make_deck(vec![
            make_slide("title"),
            make_slide("content"),
            make_slide("section_break"),
        ]);
        let sections = collect_sections(&deck);
        assert!(
            sections.is_empty(),
            "collect_sections must return an empty Vec when no slides contribute sections"
        );
    }

    /// AC-003 / EC-001 — collect_sections on an entirely empty deck (zero
    /// slides) returns an empty Vec and does not panic.
    ///
    /// FAILS at Red Gate: collect_sections returns todo!().
    #[test]
    fn test_bc_3_02_001_collect_sections_empty_deck_produces_empty_vec() {
        let deck = make_deck(vec![]);
        let sections = collect_sections(&deck);
        assert!(
            sections.is_empty(),
            "collect_sections must return an empty Vec for a zero-slide deck"
        );
    }

    /// BC-3.02.001 postcondition 4 — calling collect_sections twice on the
    /// same Deck always produces the same Vec (same length, same order, same
    /// content). Determinism is a hard invariant.
    ///
    /// FAILS at Red Gate: collect_sections returns todo!().
    #[test]
    fn test_bc_3_02_001_collect_sections_is_deterministic() {
        let deck = make_deck(vec![
            make_slide_with_takeaway("content", "Finding A"),
            make_severity_card_slide("Risk X", "Medium", "Some risk", "Owner"),
            make_slide_with_takeaway("bullets", "Finding B"),
        ]);
        let first = collect_sections(&deck);
        let second = collect_sections(&deck);
        assert_eq!(
            first, second,
            "collect_sections must be deterministic — repeated calls on the same Deck must produce equal output"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // BC-3.02.002 — manual section blocks passed through
    //
    // NOTE TO IMPLEMENTER: These tests exercise the manual section collection
    // path (AC-004). The current `slideforge_types::Deck` struct does not yet
    // have a `section_blocks` or `top_level_sections` field.  The implementer
    // must add such a field to `Deck` and update `collect_sections` to iterate
    // it.  The tests below are written against the current `Deck` struct;
    // once the field is added, additional assertions about the returned
    // ManualSection items must be added to these tests (or the tests must be
    // extended with a helper that constructs a Deck with section blocks).
    //
    // For now these tests exercise `collect_sections` with a plain deck (no
    // section blocks) and drive the Red Gate via the todo!() panic.  The
    // assertions on ManualSection kind will be strengthened in the same commit
    // that adds `Deck::section_blocks`.
    // ─────────────────────────────────────────────────────────────────────────

    /// BC-3.02.002 / AC-004 — collect_sections returns a ManuallyAuthored
    /// section with SectionKind::ManualSection("methodology") when a deck
    /// contains a manually authored `section methodology:` block.
    ///
    /// FAILS at Red Gate: collect_sections returns todo!().
    ///
    /// NOTE: This test must be strengthened after the implementer adds
    /// `Deck::section_blocks`.  For now it exercises the todo!() panic path
    /// to establish the Red Gate.  The full assertion (checking that the
    /// returned section has kind ManualSection("methodology") and source
    /// ManuallyAuthored) must be added when the field exists.
    #[test]
    fn test_bc_3_02_002_manual_section_block_passed_through() {
        // Until Deck gains a section_blocks field, we exercise the collect_sections
        // todo!() path using a plain deck.  The assertion drives Red Gate failure.
        let deck = make_deck(vec![make_slide("title")]);
        // When collect_sections is implemented it must check for section blocks;
        // this call currently panics with todo!() — the Red Gate requirement.
        let sections = collect_sections(&deck);
        // Post-implementation assertion (to be expanded when section_blocks exists):
        // a deck with no section blocks produces no ManualSection entries.
        let has_manual = sections
            .iter()
            .any(|s| matches!(s.kind, SectionKind::ManualSection(_)));
        assert!(
            !has_manual,
            "a deck with no manual section blocks must not produce any ManualSection entries"
        );
    }

    /// BC-3.02.002 / AC-004 — a ManualSection entry produced from a manually
    /// authored block must have SectionSource::ManuallyAuthored, not AutoGenerated.
    ///
    /// FAILS at Red Gate: collect_sections returns todo!().
    ///
    /// NOTE: Full assertion requires `Deck::section_blocks`.  This test
    /// establishes the Red Gate.  Once the implementer adds the field, this
    /// test must be updated to construct a deck with a section block and
    /// assert the source field is ManuallyAuthored.
    #[test]
    fn test_bc_3_02_002_manual_section_source_is_manually_authored() {
        // Exercise the todo!() path — currently panics.
        let deck = make_deck(vec![make_slide("content")]);
        let sections = collect_sections(&deck);
        // Post-implementation: all ManualSection entries must have ManuallyAuthored source.
        for section in &sections {
            if matches!(section.kind, SectionKind::ManualSection(_)) {
                assert_eq!(
                    section.source,
                    SectionSource::ManuallyAuthored,
                    "every ManualSection must have SectionSource::ManuallyAuthored"
                );
            }
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // BC-3.02.001 / AC-005 — PPTX/HTML sections excluded via target_formats tag
    // ─────────────────────────────────────────────────────────────────────────

    /// AC-005 — auto-generated sections must NOT include Pptx or Html in
    /// target_formats.  This tag is the layout engine's responsibility; exporters
    /// filter on it.
    ///
    /// FAILS at Red Gate: collect_executive_summary returns todo!().
    #[test]
    fn test_bc_3_02_001_executive_summary_excludes_pptx_and_html_from_target_formats() {
        let deck = make_deck(vec![make_slide_with_takeaway("content", "Key point")]);
        let section = collect_executive_summary(&deck).expect("must produce section");
        assert!(
            !section.target_formats.contains(&OutputFormat::Pptx),
            "executive_summary must NOT target Pptx — PPTX exporter must filter it out (AC-005)"
        );
        assert!(
            !section.target_formats.contains(&OutputFormat::Html),
            "executive_summary must NOT target Html — HTML exporter must filter it out (AC-005)"
        );
    }

    /// AC-005 — auto-generated risk_register must NOT include Pptx or Html.
    ///
    /// FAILS at Red Gate: collect_risk_register returns todo!().
    #[test]
    fn test_bc_3_02_001_risk_register_excludes_pptx_and_html_from_target_formats() {
        let deck = make_deck(vec![make_severity_card_slide(
            "Risk", "Low", "Minor", "Owner",
        )]);
        let section = collect_risk_register(&deck).expect("must produce section");
        assert!(
            !section.target_formats.contains(&OutputFormat::Pptx),
            "risk_register must NOT target Pptx (AC-005)"
        );
        assert!(
            !section.target_formats.contains(&OutputFormat::Html),
            "risk_register must NOT target Html (AC-005)"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // BC-3.02.001 / AC-005 — UnknownSectionType error variant reachability
    // ─────────────────────────────────────────────────────────────────────────

    /// EC-005 — `LayoutError::UnknownSectionType` can be constructed and
    /// displays a human-readable message containing the unknown name.
    ///
    /// This is a type-level smoke test that does not require `collect_sections`
    /// to be implemented.  It verifies that the error variant the implementer
    /// must return for unknown section type names (AC-004) exists and is
    /// usable.
    ///
    /// PASSES at Red Gate (type-only test).
    #[test]
    fn test_bc_3_02_002_unknown_section_type_error_variant_exists() {
        use crate::error::LayoutError;
        let err = LayoutError::UnknownSectionType {
            name: "frobnicator".to_owned(),
        };
        let msg = err.to_string();
        assert!(
            msg.contains("frobnicator"),
            "UnknownSectionType error must include the unknown name; got: {msg}"
        );
    }
}
