//! STORY-042 unit tests for BC-4.02.002 — Auto-Generated Document Sections.
//!
//! # Test naming convention
//!
//! `test_BC_4_02_002_<assertion_name>` — all tests trace to BC-4.02.002.
//!
//! # Red Gate status
//!
//! Every test marked **RED** will panic with `not yet implemented` when run
//! against the current stubs. Tests marked **GREEN-BY-DESIGN** or
//! **WIRING-EXEMPT** are documented with their rationale.
//!
//! # Traceability
//!
//! | Test name | BC clause | Story AC |
//! |-----------|-----------|----------|
//! | `test_BC_4_02_002_ac001_executive_summary_from_takeaway` | postcondition 2 | AC-001 |
//! | `test_BC_4_02_002_ac002_risk_register_table_row_count` | postcondition 3 | AC-002 |
//! | `test_BC_4_02_002_ac003_manual_section_heading_present` | postcondition 4 | AC-003 |
//! | `test_BC_4_02_002_ac004_section_ordering_narrative_auto_manual` | postcondition 5 | AC-004 |
//! | `test_BC_4_02_002_ac005_risk_register_absent_when_no_severity_cards` | invariant 2 | AC-005 |
//! | `test_BC_4_02_002_ac006_executive_summary_absent_when_all_takeaways_empty` | EC-004 | AC-006 |
//! | `test_BC_4_02_002_ac007_manual_section_not_merged_with_auto` | invariant 3 | AC-007 |
//! | `test_BC_4_02_002_ac008_twenty_severity_cards_twenty_rows` | EC-005 | AC-008 |
//! | `test_BC_4_02_002_styles_xml_contains_table_styles` | postcondition 2 | styles.xml req |
//! | `test_BC_4_02_002_executive_summary_two_takeaway_bullets` | postcondition 2 | AC-001 canonical vector |
//! | `test_BC_4_02_002_risk_register_three_rows_severity_labels` | postcondition 3 | BC canonical vector |
//! | `test_BC_4_02_002_section_orderer_auto_before_manual` | postcondition 5 | ordering invariant |
//! | `test_BC_4_02_002_section_orderer_empty_auto_not_returned` | invariant 2 | empty-section guard |
//! | `test_BC_4_02_002_ooxml_parse_back_document_with_sections` | postcondition 6 | structural validity |

#![allow(clippy::unwrap_used)]
#![allow(clippy::expect_used)]
#![allow(clippy::panic)]
#![allow(non_snake_case)]
#![allow(clippy::doc_markdown)]

use std::io::Read as IoRead;
use std::sync::Arc;

use slideforge_eval::BleedChecker;
use slideforge_layout::{
    sections::{GeneratedSection, OutputFormat, SectionItem, SectionKind, SectionSource},
    types::{BoundingBox, Emu, Frame, FrameContent, LaidOutDeck, LaidOutSlide, PageSize},
};
use slideforge_plugin_api::{ExportOptions, Exporter};
use slideforge_types::{
    Brand, BrandFonts, BrandPalette, Deck, DeckMetadata, OrderedMap, Register, RegisteredContent,
};

use crate::DocxExporter;

// ─── Fixture helpers ──────────────────────────────────────────────────────────

/// Build a minimal [`Brand`] for use in export tests.
fn minimal_brand() -> Brand {
    use slideforge_types::span::SourceSpan;
    Brand {
        name: Arc::from("test-brand"),
        palette: BrandPalette {
            primary: Arc::from("#003087"),
            secondary: Arc::from("#0066CC"),
            accent: Arc::from("#FF6B35"),
            neutral: Arc::from("#F5F5F5"),
        },
        fonts: BrandFonts {
            heading: Arc::from("Calibri Light"),
            body: Arc::from("Calibri"),
            mono: Arc::from("Courier New"),
        },
        layouts: vec![],
        span: SourceSpan::default(),
    }
}

/// Build a minimal [`Deck`] with `lang "en-US"`.
fn minimal_deck() -> Deck {
    Deck {
        slides: vec![],
        vars: OrderedMap::new(),
        metadata: DeckMetadata {
            title: Some(Arc::from("Test Deck")),
            slideforge_version: Arc::from("0.1.0"),
            lang: Some(Arc::from("en-US")),
            author: None,
            section_order: None,
        },
        registers: OrderedMap::new(),
        section_blocks: vec![],
    }
}

/// Build a [`LaidOutSlide`] with a given title and no register content.
fn make_slide(title: &str) -> LaidOutSlide {
    LaidOutSlide {
        source_index: 0,
        slide_type_keyword: Arc::from("content"),
        frames: vec![Frame {
            bbox: BoundingBox {
                x: Emu(0),
                y: Emu(0),
                width: Emu(9_144_000),
                height: Emu(5_143_500),
            },
            content: FrameContent::Title(Arc::from(title)),
            text_flow: None,
        }],
        speaker_notes: None,
        register_tags: vec![],
        register_content: vec![RegisteredContent::plain(
            Register::Report,
            Arc::from(format!("Report paragraph for '{title}'")),
        )],
    }
}

/// Build an auto-generated `executive_summary` [`GeneratedSection`] from a
/// list of takeaway strings.
fn make_executive_summary_section(takeaways: &[&str]) -> GeneratedSection {
    GeneratedSection {
        kind: SectionKind::ExecutiveSummary,
        source: SectionSource::AutoGenerated,
        items: takeaways
            .iter()
            .map(|t| SectionItem::TakeawayBullet(Arc::from(*t)))
            .collect(),
        heading: Arc::from("Executive Summary"),
        target_formats: vec![OutputFormat::Docx, OutputFormat::Pdf],
        register_content: vec![],
    }
}

/// Build an auto-generated `risk_register` [`GeneratedSection`] from a list
/// of `(title, severity, description)` tuples.
fn make_risk_register_section(rows: &[(&str, &str, &str)]) -> GeneratedSection {
    GeneratedSection {
        kind: SectionKind::RiskRegister,
        source: SectionSource::AutoGenerated,
        items: rows
            .iter()
            .map(|(title, severity, desc)| SectionItem::RiskRow {
                title: Arc::from(*title),
                severity: Arc::from(*severity),
                description: Arc::from(*desc),
                owner: Arc::from("TBD"),
            })
            .collect(),
        heading: Arc::from("Risk Register"),
        target_formats: vec![OutputFormat::Docx, OutputFormat::Pdf],
        register_content: vec![],
    }
}

/// Build a manually-authored [`GeneratedSection`] with the given name and
/// report content paragraph.
fn make_manual_section(name: &str, report_text: &str) -> GeneratedSection {
    GeneratedSection {
        kind: SectionKind::ManualSection(Arc::from(name)),
        source: SectionSource::ManuallyAuthored,
        items: vec![],
        heading: Arc::from(capitalize_first(name)),
        target_formats: vec![OutputFormat::Docx, OutputFormat::Pdf],
        register_content: vec![RegisteredContent::plain(
            Register::Report,
            Arc::from(report_text),
        )],
    }
}

/// Capitalize the first character of a string (for heading generation).
fn capitalize_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
    }
}

/// Build a [`LaidOutDeck`] wrapping the provided slides and sections.
fn make_laid_out_deck(slides: Vec<LaidOutSlide>, sections: Vec<GeneratedSection>) -> LaidOutDeck {
    LaidOutDeck {
        page_size: PageSize::default(),
        slides,
        sections,
        warnings: vec![],
    }
}

/// Call `DocxExporter::export` and return the raw `.docx` bytes.
fn export_deck(deck: &Deck, laid_out: &LaidOutDeck) -> Vec<u8> {
    let brand = minimal_brand();
    let opts = ExportOptions::default();
    DocxExporter
        .export(deck, laid_out, &brand, &opts)
        .expect("export must succeed")
}

/// Read a named ZIP member from a `.docx` byte buffer as a UTF-8 string.
fn read_zip_member(docx_bytes: &[u8], name: &str) -> String {
    let cursor = std::io::Cursor::new(docx_bytes);
    let mut archive = zip::ZipArchive::new(cursor).expect("valid zip");
    let mut entry = archive.by_name(name).expect("member must exist");
    let mut buf = String::new();
    entry.read_to_string(&mut buf).expect("valid utf-8");
    buf
}

/// Collect the byte positions of all `Heading1` occurrences in a document XML
/// string.
///
/// Used by ordering tests to assert that narrative headings precede section
/// headings. Returns positions in document order (increasing).
#[allow(dead_code)] // used in AC-004 ordering assertion and future snapshot tests
fn find_heading1_positions(doc_xml: &str) -> Vec<usize> {
    let mut positions = Vec::new();
    let mut search = doc_xml;
    let mut base_offset = 0_usize;

    while let Some(rel_pos) = search.find("Heading1") {
        let abs_pos = base_offset + rel_pos;
        positions.push(abs_pos);
        let advance = rel_pos + "Heading1".len();
        base_offset += advance;
        search = &search[rel_pos + "Heading1".len()..];
    }
    positions
}

// ─── AC-001: executive_summary from takeaway fields ───────────────────────────

/// BC-4.02.002 postcondition 2 / AC-001:
/// A 2-slide deck where each slide has a takeaway produces a DOCX with:
/// 1. A `Heading1` paragraph "Executive Summary"
/// 2. Two bullet paragraphs: "Key finding: X" and "Key finding: Y"
///
/// RED: will panic at `todo!()` in section serialization.
#[test]
fn test_BC_4_02_002_ac001_executive_summary_from_takeaway() {
    let deck = minimal_deck();
    let slide1 = make_slide("Slide One");
    let slide2 = {
        let mut s = make_slide("Slide Two");
        s.source_index = 1;
        s
    };
    let exec_summary = make_executive_summary_section(&["Key finding: X", "Key finding: Y"]);
    let laid_out = make_laid_out_deck(vec![slide1, slide2], vec![exec_summary]);

    let docx_bytes = export_deck(&deck, &laid_out);
    let doc_xml = read_zip_member(&docx_bytes, "word/document.xml");

    assert!(
        doc_xml.contains("Executive Summary"),
        "word/document.xml must contain 'Executive Summary' heading (AC-001); \
         got:\n{doc_xml}"
    );
    assert!(
        doc_xml.contains("Key finding: X"),
        "word/document.xml must contain takeaway 'Key finding: X' (AC-001)"
    );
    assert!(
        doc_xml.contains("Key finding: Y"),
        "word/document.xml must contain takeaway 'Key finding: Y' (AC-001)"
    );
}

// ─── AC-001 canonical test vector (BC-4.02.002 canonical test vectors table) ──

/// BC-4.02.002 canonical test vector / AC-001:
/// `Deck with takeaway "Key finding: X" on 2 slides` →
/// `.docx executive_summary section with 2 takeaway paragraphs`.
///
/// RED: will panic at `todo!()` in section serialization.
#[test]
fn test_BC_4_02_002_executive_summary_two_takeaway_bullets() {
    let deck = minimal_deck();
    let slide = make_slide("Insights Slide");
    let exec_summary = make_executive_summary_section(&["Key finding: Alpha", "Key finding: Beta"]);
    let laid_out = make_laid_out_deck(vec![slide], vec![exec_summary]);

    let docx_bytes = export_deck(&deck, &laid_out);
    let doc_xml = read_zip_member(&docx_bytes, "word/document.xml");

    // Must have the heading.
    assert!(
        doc_xml.contains("Executive Summary"),
        "document.xml must contain 'Executive Summary' heading (canonical test vector)"
    );

    // Both takeaway texts must appear.
    assert!(
        doc_xml.contains("Key finding: Alpha"),
        "document.xml must contain first takeaway bullet (canonical test vector)"
    );
    assert!(
        doc_xml.contains("Key finding: Beta"),
        "document.xml must contain second takeaway bullet (canonical test vector)"
    );

    // Count occurrences of each takeaway — they must each appear exactly once.
    let count_alpha = doc_xml.matches("Key finding: Alpha").count();
    let count_beta = doc_xml.matches("Key finding: Beta").count();
    assert_eq!(
        count_alpha, 1,
        "first takeaway must appear exactly once; found {count_alpha}"
    );
    assert_eq!(
        count_beta, 1,
        "second takeaway must appear exactly once; found {count_beta}"
    );
}

// ─── AC-002: risk_register table from severity_cards slides ───────────────────

/// BC-4.02.002 postcondition 3 / AC-002:
/// A deck with 3 `severity_cards` (HIGH, MED, LOW) produces a DOCX with:
/// 1. A `Heading1` paragraph "Risk Register"
/// 2. A `<w:tbl>` with 1 header row + 3 data rows (4 total)
///
/// RED: will panic at `todo!()` in section serialization.
#[test]
fn test_BC_4_02_002_ac002_risk_register_table_row_count() {
    let deck = minimal_deck();
    let slide = make_slide("Risk Slide");
    let risk_register = make_risk_register_section(&[
        ("R001", "HIGH", "Infrastructure outage risk"),
        ("R002", "MED", "Vendor dependency risk"),
        ("R003", "LOW", "Documentation gap"),
    ]);
    let laid_out = make_laid_out_deck(vec![slide], vec![risk_register]);

    let docx_bytes = export_deck(&deck, &laid_out);
    let doc_xml = read_zip_member(&docx_bytes, "word/document.xml");

    assert!(
        doc_xml.contains("Risk Register"),
        "word/document.xml must contain 'Risk Register' heading (AC-002)"
    );
    assert!(
        doc_xml.contains("<w:tbl"),
        "word/document.xml must contain a <w:tbl> table for risk register (AC-002)"
    );

    // Count table rows: 1 header + 3 data = 4 total.
    let tr_count = doc_xml.matches("<w:tr").count();
    assert_eq!(
        tr_count, 4,
        "risk register table must have 4 rows (1 header + 3 data); found {tr_count} <w:tr> \
         elements (AC-002)"
    );
}

// ─── AC-002 canonical test vector ─────────────────────────────────────────────

/// BC-4.02.002 canonical test vector / AC-002:
/// `Deck with 3 severity_cards slides (HIGH, MED, LOW)` →
/// `.docx risk_register section with 3-row table; severity labels present`.
///
/// RED: will panic at `todo!()` in section serialization.
#[test]
fn test_BC_4_02_002_risk_register_three_rows_severity_labels() {
    let deck = minimal_deck();
    let slide = make_slide("Risk Overview");
    let risk_register = make_risk_register_section(&[
        ("R001", "HIGH", "Infrastructure outage risk"),
        ("R002", "MED", "Vendor dependency risk"),
        ("R003", "LOW", "Documentation gap"),
    ]);
    let laid_out = make_laid_out_deck(vec![slide], vec![risk_register]);

    let docx_bytes = export_deck(&deck, &laid_out);
    let doc_xml = read_zip_member(&docx_bytes, "word/document.xml");

    // Severity labels must appear in the table.
    assert!(
        doc_xml.contains("HIGH"),
        "risk register table must contain severity label HIGH (canonical vector)"
    );
    assert!(
        doc_xml.contains("MED"),
        "risk register table must contain severity label MED (canonical vector)"
    );
    assert!(
        doc_xml.contains("LOW"),
        "risk register table must contain severity label LOW (canonical vector)"
    );

    // Risk titles must appear.
    assert!(
        doc_xml.contains("R001"),
        "risk register table must contain title R001 (canonical vector)"
    );
    assert!(
        doc_xml.contains("Infrastructure outage risk"),
        "risk register table must contain description text (canonical vector)"
    );

    // Header row columns: Risk, Severity, Description.
    assert!(
        doc_xml.contains("Risk"),
        "risk register table header must contain column 'Risk' (canonical vector)"
    );
    assert!(
        doc_xml.contains("Severity"),
        "risk register table header must contain column 'Severity' (canonical vector)"
    );
    assert!(
        doc_xml.contains("Description"),
        "risk register table header must contain column 'Description' (canonical vector)"
    );
}

// ─── AC-003: manually-authored section at declared position ───────────────────

/// BC-4.02.002 postcondition 4 / AC-003:
/// A deck with a `section methodology:` block produces a DOCX with a
/// "Methodology" `Heading1` and the authored content.
///
/// RED: will panic at `todo!()` in section serialization.
#[test]
fn test_BC_4_02_002_ac003_manual_section_heading_present() {
    let deck = minimal_deck();
    let slide = make_slide("Main Slide");
    let methodology = make_manual_section(
        "methodology",
        "Our methodology involved quantitative and qualitative analysis.",
    );
    let laid_out = make_laid_out_deck(vec![slide], vec![methodology]);

    let docx_bytes = export_deck(&deck, &laid_out);
    let doc_xml = read_zip_member(&docx_bytes, "word/document.xml");

    assert!(
        doc_xml.contains("Methodology"),
        "word/document.xml must contain 'Methodology' heading (AC-003)"
    );
    assert!(
        doc_xml.contains("quantitative and qualitative analysis"),
        "word/document.xml must contain the manual section body text (AC-003)"
    );
}

// ─── AC-004: section ordering (narrative → auto → manual) ────────────────────

/// BC-4.02.002 postcondition 5 / AC-004:
/// A deck with narrative slides + risk_register (auto) + methodology (manual)
/// produces a DOCX where the order is:
/// 1. Per-slide narrative headings (Heading1 for slides)
/// 2. "Risk Register" (auto)
/// 3. "Methodology" (manual)
///
/// RED: will panic at `todo!()` in section serialization.
#[test]
fn test_BC_4_02_002_ac004_section_ordering_narrative_auto_manual() {
    let deck = minimal_deck();
    let slide = make_slide("Q1 Analysis");
    let risk_register = make_risk_register_section(&[("R001", "HIGH", "Critical risk item")]);
    let methodology = make_manual_section("methodology", "Methodology body text.");
    // sections: auto before manual in the sections vec per BC-4.02.002 ordering
    let laid_out = make_laid_out_deck(vec![slide], vec![risk_register, methodology]);

    let docx_bytes = export_deck(&deck, &laid_out);
    let doc_xml = read_zip_member(&docx_bytes, "word/document.xml");

    // All three headings must be present.
    assert!(
        doc_xml.contains("Q1 Analysis"),
        "narrative heading 'Q1 Analysis' must be present (AC-004)"
    );
    assert!(
        doc_xml.contains("Risk Register"),
        "'Risk Register' heading must be present (AC-004)"
    );
    assert!(
        doc_xml.contains("Methodology"),
        "'Methodology' heading must be present (AC-004)"
    );

    // Order assertion: narrative < risk register < methodology.
    let narrative_pos = doc_xml
        .find("Q1 Analysis")
        .expect("narrative heading must be in document.xml");
    let risk_pos = doc_xml
        .find("Risk Register")
        .expect("Risk Register heading must be in document.xml");
    let methodology_pos = doc_xml
        .find("Methodology")
        .expect("Methodology heading must be in document.xml");

    assert!(
        narrative_pos < risk_pos,
        "narrative heading must appear BEFORE risk register (AC-004 postcondition 5): \
         narrative at {narrative_pos}, risk_register at {risk_pos}"
    );
    assert!(
        risk_pos < methodology_pos,
        "risk register must appear BEFORE methodology (AC-004 postcondition 5): \
         risk_register at {risk_pos}, methodology at {methodology_pos}"
    );
}

// ─── AC-005: auto-section absent when no source slides ────────────────────────

/// BC-4.02.002 invariant 2 / AC-005:
/// A deck with no `severity_cards` slides (no risk_register section in IR)
/// produces a DOCX with NO "Risk Register" section.
///
/// RED: implicitly depends on the correct behavior — if serialize_section is
/// called on an empty-items section and panics at todo!(), this will fail there.
/// The assertion will also fail if sections are incorrectly emitted.
#[test]
fn test_BC_4_02_002_ac005_risk_register_absent_when_no_severity_cards() {
    let deck = minimal_deck();
    let slide = make_slide("Normal Slide");
    // No risk_register section in the LaidOutDeck.sections.
    let laid_out = make_laid_out_deck(vec![slide], vec![]);

    let docx_bytes = export_deck(&deck, &laid_out);
    let doc_xml = read_zip_member(&docx_bytes, "word/document.xml");

    assert!(
        !doc_xml.contains("Risk Register"),
        "word/document.xml must NOT contain 'Risk Register' when no risk sections \
         are present (AC-005 / BC-4.02.002 invariant 2); got:\n{doc_xml}"
    );
    assert!(
        !doc_xml.contains("<w:tbl"),
        "word/document.xml must NOT contain any table when no risk register section \
         is present (AC-005)"
    );

    // BleedChecker: "Risk Register" must not appear anywhere in the DOCX body.
    BleedChecker::assert_absent_from_docx_body(&docx_bytes, "Risk Register");
}

// ─── AC-006: executive_summary absent when all takeaway fields empty ──────────

/// BC-4.02.002 EC-004 / AC-006:
/// A deck where all slides have no takeaways (no executive_summary in IR)
/// produces a DOCX with NO "Executive Summary" section.
///
/// RED: assertion will fail if sections are incorrectly emitted.
#[test]
fn test_BC_4_02_002_ac006_executive_summary_absent_when_all_takeaways_empty() {
    let deck = minimal_deck();
    let slide = make_slide("Slide Without Takeaway");
    // No executive_summary section in sections.
    let laid_out = make_laid_out_deck(vec![slide], vec![]);

    let docx_bytes = export_deck(&deck, &laid_out);
    let doc_xml = read_zip_member(&docx_bytes, "word/document.xml");

    assert!(
        !doc_xml.contains("Executive Summary"),
        "word/document.xml must NOT contain 'Executive Summary' when no takeaways \
         are present (AC-006 / BC-4.02.002 EC-004); got:\n{doc_xml}"
    );

    // BleedChecker: "Executive Summary" must not appear in the DOCX body.
    BleedChecker::assert_absent_from_docx_body(&docx_bytes, "Executive Summary");
}

// ─── AC-007: manual section NOT merged with auto-generated section ─────────────

/// BC-4.02.002 invariant 3 / AC-007:
/// A deck with only a manual `section methodology:` produces exactly ONE
/// "Methodology" heading. There must not be a duplicate auto-generated section
/// of the same name (since no auto-methodology rule exists by default).
///
/// RED: will panic at `todo!()` in section serialization.
#[test]
fn test_BC_4_02_002_ac007_manual_section_not_merged_with_auto() {
    let deck = minimal_deck();
    let slide = make_slide("Analysis Slide");
    let methodology = make_manual_section("methodology", "Manual methodology text.");
    // Only one manual section — no auto-generated section of the same name.
    let laid_out = make_laid_out_deck(vec![slide], vec![methodology]);

    let docx_bytes = export_deck(&deck, &laid_out);
    let doc_xml = read_zip_member(&docx_bytes, "word/document.xml");

    // "Methodology" heading must appear exactly once (the manual section).
    let count = doc_xml.matches("Methodology").count();
    assert!(
        count >= 1,
        "word/document.xml must contain at least one 'Methodology' occurrence \
         for the manual section (AC-007)"
    );

    // The manual section body must be present.
    assert!(
        doc_xml.contains("Manual methodology text."),
        "word/document.xml must contain the manual section body text (AC-007)"
    );
}

// ─── AC-008: 20 severity_cards → 20-row table ────────────────────────────────

/// BC-4.02.002 EC-005 / AC-008:
/// A deck with 20 severity_cards slides produces a risk_register table with
/// exactly 20 data rows (21 total rows including the header).
///
/// RED: will panic at `todo!()` in section serialization.
#[test]
fn test_BC_4_02_002_ac008_twenty_severity_cards_twenty_rows() {
    let deck = minimal_deck();
    let slide = make_slide("Risk Overview");

    // Build 20 RiskRow items.
    let rows: Vec<(&str, &str, &str)> = (0..20)
        .map(|i| {
            // Use static strings — Rust requires string literals for this pattern.
            // We build the strings inline via leak (test-only allocation).
            let title: &'static str = Box::leak(format!("R{i:03}").into_boxed_str());
            let severity: &'static str = if i % 3 == 0 {
                "HIGH"
            } else if i % 3 == 1 {
                "MED"
            } else {
                "LOW"
            };
            let desc: &'static str =
                Box::leak(format!("Risk description for item {i}").into_boxed_str());
            (title, severity, desc)
        })
        .collect();

    // Convert to &str tuples and build section.
    let row_refs: Vec<(&str, &str, &str)> = rows
        .iter()
        .map(|&(t, s, d)| (t, s, d))
        .collect();

    let risk_register = make_risk_register_section(&row_refs);
    let laid_out = make_laid_out_deck(vec![slide], vec![risk_register]);

    let docx_bytes = export_deck(&deck, &laid_out);
    let doc_xml = read_zip_member(&docx_bytes, "word/document.xml");

    // Count <w:tr elements: 1 header + 20 data = 21.
    let tr_count = doc_xml.matches("<w:tr").count();
    assert_eq!(
        tr_count, 21,
        "risk register table must have 21 rows (1 header + 20 data) for 20 risk items; \
         found {tr_count} <w:tr> elements (AC-008 / BC-4.02.002 EC-005)"
    );
}

// ─── styles.xml: TableGrid and TableHeader styles present ────────────────────

/// BC-4.02.002 / STORY-042 styles.xml requirement:
/// `word/styles.xml` must define `TableGrid` (table style) and `TableHeader`
/// (character/paragraph style for header cells) after STORY-042.
///
/// RED: will fail because styles.xml currently does not define these styles.
#[test]
fn test_BC_4_02_002_styles_xml_contains_table_styles() {
    let deck = minimal_deck();
    let slide = make_slide("Style Check");
    let laid_out = make_laid_out_deck(vec![slide], vec![]);

    let docx_bytes = export_deck(&deck, &laid_out);
    let styles_xml = read_zip_member(&docx_bytes, "word/styles.xml");

    assert!(
        styles_xml.contains("TableGrid"),
        "word/styles.xml must define TableGrid table style (STORY-042 styles.xml req); \
         got:\n{styles_xml}"
    );
    assert!(
        styles_xml.contains("TableHeader"),
        "word/styles.xml must define TableHeader style (STORY-042 styles.xml req); \
         got:\n{styles_xml}"
    );
}

// ─── SectionOrderer unit tests ────────────────────────────────────────────────

/// BC-4.02.002 postcondition 5 (ordering) — `SectionOrderer`:
/// Auto-generated sections are returned before manually-authored sections.
///
/// RED: will panic at `todo!()` in `SectionOrderer::ordered_sections`.
#[test]
fn test_BC_4_02_002_section_orderer_auto_before_manual() {
    use crate::section_order::SectionOrderer;

    let slide = make_slide("Test");
    let risk_register = make_risk_register_section(&[("R001", "HIGH", "Risk")]);
    let methodology = make_manual_section("methodology", "Methodology body.");
    // sections vec: [risk_register (auto), methodology (manual)]
    let laid_out = make_laid_out_deck(vec![slide], vec![risk_register, methodology]);

    let orderer = SectionOrderer::new(&laid_out);
    let ordered = orderer.ordered_sections();

    assert_eq!(
        ordered.len(),
        2,
        "ordered_sections must return both sections; got {}",
        ordered.len()
    );

    // First section must be auto-generated (risk_register).
    assert_eq!(
        ordered[0].source,
        SectionSource::AutoGenerated,
        "first section in ordered output must be AutoGenerated (postcondition 5)"
    );

    // Second section must be manually-authored (methodology).
    assert_eq!(
        ordered[1].source,
        SectionSource::ManuallyAuthored,
        "second section in ordered output must be ManuallyAuthored (postcondition 5)"
    );
}

/// BC-4.02.002 invariant 2 (empty-section guard) — `SectionOrderer::auto_sections`:
/// An auto-generated section with zero items must NOT be returned.
///
/// RED: will panic at `todo!()` in `SectionOrderer::auto_sections`.
#[test]
fn test_BC_4_02_002_section_orderer_empty_auto_not_returned() {
    use crate::section_order::SectionOrderer;

    let slide = make_slide("Test");
    // Build an empty auto-generated section (0 items).
    let empty_exec_summary = GeneratedSection {
        kind: SectionKind::ExecutiveSummary,
        source: SectionSource::AutoGenerated,
        items: vec![], // empty — must not be returned by auto_sections()
        heading: Arc::from("Executive Summary"),
        target_formats: vec![OutputFormat::Docx, OutputFormat::Pdf],
        register_content: vec![],
    };
    let laid_out = make_laid_out_deck(vec![slide], vec![empty_exec_summary]);

    let orderer = SectionOrderer::new(&laid_out);
    let auto = orderer.auto_sections();

    assert!(
        auto.is_empty(),
        "auto_sections() must return empty vec for a section with zero items \
         (BC-4.02.002 invariant 2 empty-section guard); got {} sections",
        auto.len()
    );
}

// ─── Structural OOXML parse-back with sections present ────────────────────────

/// BC-4.02.002 postcondition 6 / structural validity:
/// `word/document.xml` must parse back through ooxmlsdk after a deck with
/// both auto and manual sections is exported.
///
/// RED: will panic at `todo!()` in section serialization.
#[test]
fn test_BC_4_02_002_ooxml_parse_back_document_with_sections() {
    use ooxmlsdk::schemas::schemas_openxmlformats_org_wordprocessingml_2006_main::Document;
    #[allow(unused_imports)]
    use ooxmlsdk::sdk::SdkType;

    let deck = minimal_deck();
    let slide = make_slide("Overview Slide");
    let exec_summary = make_executive_summary_section(&["Key finding: Production is stable."]);
    let risk_register = make_risk_register_section(&[("R001", "HIGH", "Critical infrastructure")]);
    let methodology = make_manual_section("methodology", "Standard methodology applied.");
    let laid_out = make_laid_out_deck(
        vec![slide],
        vec![exec_summary, risk_register, methodology],
    );

    let docx_bytes = export_deck(&deck, &laid_out);
    let doc_xml = read_zip_member(&docx_bytes, "word/document.xml");

    let document = Document::from_bytes(doc_xml.as_bytes()).unwrap_or_else(|e| {
        panic!(
            "word/document.xml must deserialize through ooxmlsdk::Document without error \
             after section serialization (BC-4.02.002 postcondition 6); \
             error: {e}\nGot:\n{doc_xml}"
        )
    });

    assert!(
        document.body.is_some(),
        "word/document.xml must have a <w:body> element after ooxmlsdk parse-back \
         with sections present (BC-4.02.002 postcondition 6)"
    );
}

// ─── BC-4.02.002 canonical test vector: no auto-generatable slides ────────────

/// BC-4.02.002 canonical test vector:
/// `Deck with no auto-generatable slides` →
/// `.docx has only per-slide narrative body; no auto sections`.
///
/// WIRING-EXEMPT: This test verifies an already-working path (empty sections
/// vec → no section XML emitted). It passes today because `DocumentBodySerializer`
/// already handles the empty `sections` case correctly — it does not call any
/// section serializer. The test is included for BC completeness and regression
/// coverage. Rationale: if Step 4 introduces a regression where section
/// serializers are called on an empty list and panic, this test catches it.
#[test]
fn test_BC_4_02_002_canonical_no_auto_sections_in_deck() {
    let deck = minimal_deck();
    let slide = make_slide("Solo Slide");
    // No sections at all in LaidOutDeck.sections.
    let laid_out = make_laid_out_deck(vec![slide], vec![]);

    let docx_bytes = export_deck(&deck, &laid_out);
    let doc_xml = read_zip_member(&docx_bytes, "word/document.xml");

    // The per-slide narrative heading must be present.
    assert!(
        doc_xml.contains("Solo Slide"),
        "per-slide heading 'Solo Slide' must be present in document.xml (canonical vector)"
    );

    // No auto-section headings.
    assert!(
        !doc_xml.contains("Executive Summary"),
        "document.xml must NOT contain 'Executive Summary' when no takeaways (canonical vector)"
    );
    assert!(
        !doc_xml.contains("Risk Register"),
        "document.xml must NOT contain 'Risk Register' when no risk sections (canonical vector)"
    );
    assert!(
        !doc_xml.contains("<w:tbl"),
        "document.xml must NOT contain any table when no risk sections (canonical vector)"
    );
}
