//! Auto-generated document section serializer for DOCX output.
//!
//! [`AutoSectionSerializer`] converts a [`slideforge_layout::sections::GeneratedSection`]
//! with [`slideforge_layout::sections::SectionSource::AutoGenerated`] into
//! `<w:body>` XML paragraphs (for executive summary) or a `<w:tbl>` table (for
//! risk register).
//!
//! ## Dispatch model (BC-4.02.002 invariant 1 / DI-008)
//!
//! Section rendering is dispatched on the section kind — no hardcoded
//! `if section_name == "executive_summary"` chains. The dispatcher calls the
//! appropriate serialization helper based on [`slideforge_layout::sections::SectionKind`]:
//!
//! | `SectionKind` | Rendered as |
//! |--------------|------------|
//! | `ExecutiveSummary` | `Heading1` + bullet `Normal` paragraphs |
//! | `RiskRegister`     | `Heading1` + `<w:tbl>` with header + data rows |
//!
//! ## Empty-section guard (BC-4.02.002 invariant 2)
//!
//! If [`GeneratedSection::items`] is empty, the serializer returns an empty
//! `Vec` — no XML is emitted for the section. Callers must not emit an empty
//! `Heading1` without content.
//!
//! ## ooxmlsdk usage
//!
//! All `<w:tbl>`, `<w:tr>`, `<w:tc>` elements are constructed via ooxmlsdk
//! typed builders (BC-4.02.002 Architecture rule 4). No string XML
//! concatenation for dynamic content.

use ooxmlsdk::schemas::schemas_openxmlformats_org_wordprocessingml_2006_main::{
    BodyChoice, GridColumn, Languages, Paragraph, ParagraphChoice, ParagraphProperties,
    ParagraphStyleId, Run, RunChoice, RunProperties, Table, TableCell, TableCellChoice,
    TableChoice2, TableGrid, TableProperties, TableRow, TableRowChoice, TableStyle, TableWidth,
    TableWidthUnitValues, Text,
};
use slideforge_layout::sections::{GeneratedSection, SectionItem, SectionKind};

use crate::error::ExportError;
use crate::xml_escape::strip_xml10_invalid_chars;

/// Serializes auto-generated [`GeneratedSection`] entries into `<w:body>` XML.
///
/// Dispatches on [`slideforge_layout::sections::SectionKind`] to select the
/// appropriate rendering helper. Returns an empty `Vec` for sections with no
/// items (BC-4.02.002 invariant 2).
pub struct AutoSectionSerializer {
    /// BCP-47 language tag threaded to every emitted run (BC-5.01.005 PC-4).
    lang: String,
}

impl AutoSectionSerializer {
    /// Create a new serializer with the given BCP-47 language tag.
    ///
    /// The `lang` value is placed in `<w:rPr><w:lang w:val="..."/>` on every
    /// run emitted by this serializer (BC-5.01.005 PC-4 universality).
    #[must_use]
    pub fn new(lang: &str) -> Self {
        Self {
            lang: lang.to_owned(),
        }
    }

    /// Serialize one auto-generated section into a list of [`BodyChoice`] elements.
    ///
    /// Returns an empty `Vec` if `section.items` is empty (invariant 2).
    ///
    /// # Errors
    ///
    /// Returns [`ExportError::OoxmlError`] if OOXML construction fails.
    pub fn serialize_section(
        &self,
        section: &GeneratedSection,
    ) -> Result<Vec<BodyChoice>, ExportError> {
        // Invariant 2: empty items → no output.
        if section.items.is_empty() {
            return Ok(vec![]);
        }

        match &section.kind {
            SectionKind::RiskRegister => serialize_risk_register(section, &self.lang),
            // ExecutiveSummary and ManualSection both render as heading + bullet list.
            // ManualSection should not normally be dispatched here (ManualSectionSerializer
            // handles it), but for robustness the fallback mirrors ExecutiveSummary rendering.
            SectionKind::ExecutiveSummary | SectionKind::ManualSection(_) => {
                serialize_executive_summary(section, &self.lang)
            },
        }
    }
}

impl Default for AutoSectionSerializer {
    fn default() -> Self {
        Self::new(crate::DEFAULT_DECK_LANG)
    }
}

/// Serialize an executive-summary section into a `Heading1` paragraph followed
/// by one `Normal` paragraph per `TakeawayBullet` item.
///
/// Returns an empty `Vec` when `section.items` is empty (invariant 2).
///
/// # Errors
///
/// Returns [`ExportError::OoxmlError`] on OOXML construction failure.
pub fn serialize_executive_summary(
    section: &GeneratedSection,
    lang: &str,
) -> Result<Vec<BodyChoice>, ExportError> {
    if section.items.is_empty() {
        return Ok(vec![]);
    }

    let mut output: Vec<BodyChoice> = Vec::new();

    // Heading1 paragraph for section title.
    output.push(BodyChoice::WP(Box::new(make_styled_paragraph(
        "Heading1",
        section.heading.as_ref(),
        lang,
    ))));

    // One Normal paragraph per TakeawayBullet item.
    for item in &section.items {
        if let SectionItem::TakeawayBullet(text) = item {
            output.push(BodyChoice::WP(Box::new(make_styled_paragraph(
                "Normal",
                text.as_ref(),
                lang,
            ))));
        }
    }

    Ok(output)
}

/// Serialize a risk-register section into a `Heading1` paragraph followed by a
/// `<w:tbl>` with one header row and one data row per `RiskRow` item.
///
/// Returns an empty `Vec` when `section.items` is empty (invariant 2).
///
/// The table uses `TableGrid` style and `TableHeader` cell style for header
/// cells (STORY-042 spec / styles.xml requirement).
///
/// # Errors
///
/// Returns [`ExportError::OoxmlError`] on OOXML construction failure.
pub fn serialize_risk_register(
    section: &GeneratedSection,
    lang: &str,
) -> Result<Vec<BodyChoice>, ExportError> {
    if section.items.is_empty() {
        return Ok(vec![]);
    }

    let mut output: Vec<BodyChoice> = Vec::new();

    // Heading1 paragraph for section title.
    output.push(BodyChoice::WP(Box::new(make_styled_paragraph(
        "Heading1",
        section.heading.as_ref(),
        lang,
    ))));

    // Build the risk register table.
    let table = build_risk_register_table(section, lang);
    output.push(BodyChoice::WTbl(Box::new(table)));

    Ok(output)
}

/// Build the `<w:tbl>` element for a risk register section.
///
/// Structure:
/// - `<w:tblPr>` with `<w:tblStyle w:val="TableGrid"/>` and auto-width
/// - `<w:tblGrid>` with one `<w:gridCol>` per column (ECMA-376 `CT_Tbl` minOccurs=1)
///   Columns: Risk | Severity | Description (3 columns, equal auto width)
/// - Header row: Risk | Severity | Description (using `TableHeader` paragraph style)
/// - Data rows: one per `SectionItem::RiskRow`
fn build_risk_register_table(section: &GeneratedSection, lang: &str) -> Table {
    let mut table_rows: Vec<TableChoice2> = Vec::new();

    // Header row.
    table_rows.push(TableChoice2::WTr(Box::new(build_table_row(
        &[("Risk", true), ("Severity", true), ("Description", true)],
        lang,
    ))));

    // Data rows — one per RiskRow item.
    for item in &section.items {
        if let SectionItem::RiskRow {
            title,
            severity,
            description,
            ..
        } = item
        {
            table_rows.push(TableChoice2::WTr(Box::new(build_table_row(
                &[
                    (title.as_ref(), false),
                    (severity.as_ref(), false),
                    (description.as_ref(), false),
                ],
                lang,
            ))));
        }
    }

    // ECMA-376 CT_Tbl requires exactly one <w:tblGrid> (minOccurs=1) after
    // <w:tblPr> and before the rows, containing one <w:gridCol> per column.
    // Without this, the table is schema-invalid and collapses in strict OOXML
    // validators (LibreOffice, Word strict mode). The risk register has 3 columns.
    let tbl_grid = TableGrid {
        w_grid_col: vec![
            GridColumn { width: None },
            GridColumn { width: None },
            GridColumn { width: None },
        ],
        ..TableGrid::default()
    };

    Table {
        w_tbl_pr: Some(Box::new(TableProperties {
            table_style: Some(TableStyle {
                val: ooxmlsdk::simple_type::StringValue::from("TableGrid"),
            }),
            table_width: Some(TableWidth {
                width: Some(ooxmlsdk::simple_type::StringValue::from("0")),
                r#type: Some(TableWidthUnitValues::Auto),
            }),
            ..TableProperties::default()
        })),
        w_tbl_grid: Some(Box::new(tbl_grid)),
        table_choice2: table_rows,
        ..Table::default()
    }
}

/// Build a `<w:tr>` element containing `<w:tc>` cells.
///
/// Each cell is given a paragraph with text. When `is_header` is `true`, the
/// paragraph uses the `TableHeader` style; otherwise it uses `Normal`.
fn build_table_row(cells: &[(&str, bool)], lang: &str) -> TableRow {
    let row_cells: Vec<TableRowChoice> = cells
        .iter()
        .map(|(text, is_header)| {
            let style = if *is_header { "TableHeader" } else { "Normal" };
            let para = make_styled_paragraph(style, text, lang);
            let cell = TableCell {
                table_cell_choice: vec![TableCellChoice::WP(Box::new(para))],
                ..TableCell::default()
            };
            TableRowChoice::WTc(Box::new(cell))
        })
        .collect();

    TableRow {
        table_row_choice: row_cells,
        ..TableRow::default()
    }
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

/// Build a paragraph with the given style containing a single plain-text run.
///
/// The run carries `<w:rPr><w:lang w:val="LANG"/></w:rPr>` so that every run
/// emitted by this serializer satisfies the BC-5.01.005 PC-4 universality
/// requirement (all runs must have lang — mirrors `make_lang_run` in
/// `document_body.rs`).
fn make_styled_paragraph(style: &str, text: &str, lang: &str) -> Paragraph {
    let sanitized = strip_xml10_invalid_chars(text);
    let needs_preserve = sanitized.starts_with(' ')
        || sanitized.ends_with(' ')
        || sanitized.starts_with('\t')
        || sanitized.ends_with('\t');

    Paragraph {
        paragraph_properties: Some(Box::new(ParagraphProperties {
            paragraph_style_id: Some(ParagraphStyleId {
                val: style.to_owned(),
            }),
            ..ParagraphProperties::default()
        })),
        paragraph_choice: vec![ParagraphChoice::WR(Box::new(Run {
            run_properties: Some(Box::new(RunProperties {
                languages: Some(Languages {
                    val: Some(lang.to_owned()),
                    ..Languages::default()
                }),
                ..RunProperties::default()
            })),
            run_choice: vec![RunChoice::WT(Box::new(Text {
                xml_content: Some(sanitized),
                space: if needs_preserve {
                    Some(ooxmlsdk::schemas::xml::SpaceProcessingModeValues::Preserve)
                } else {
                    None
                },
                ..Text::default()
            }))],
            ..Run::default()
        }))],
        ..Paragraph::default()
    }
}
