//! Document section ordering for DOCX output.
//!
//! [`SectionOrderer`] implements BC-4.02.002 postcondition 5 — the required
//! document structure ordering:
//!
//! ```text
//! 1. Per-slide narrative body (from STORY-041 / BC-4.02.001)
//! 2. Auto-generated sections (ExecutiveSummary, RiskRegister, …)
//! 3. Manually-authored sections (methodology, scope, appendix, …)
//!    unless a manual section declares an earlier position
//! ```
//!
//! ## Ordering algorithm
//!
//! `SectionOrderer::ordered_sections` returns the `&[GeneratedSection]` slice
//! from `LaidOutDeck.sections` partitioned and sorted by:
//! 1. `SectionSource::ManuallyAuthored` sections at their declared position
//!    (position index from `LaidOutDeck.sections` order).
//! 2. `SectionSource::AutoGenerated` sections in kind order (ExecutiveSummary
//!    before RiskRegister).
//!
//! The narrative body paragraphs (per-slide Heading1 + Normal content) are
//! written by `DocumentBodySerializer` BEFORE `SectionOrderer` output —
//! they are not included in this struct's output.
//!
//! ## BC-4.02.002 invariant 3 — no merging
//!
//! Manual sections are placed at their declared position, NOT merged with
//! auto-generated sections of the same name.

use slideforge_layout::{
    sections::{GeneratedSection, SectionSource},
    LaidOutDeck,
};

/// Orders document sections for `DocumentBodySerializer` consumption.
///
/// Reads `LaidOutDeck.sections` and returns two ordered lists:
/// - `auto_sections()`: auto-generated sections in kind order
/// - `manual_sections()`: manually-authored sections in declared order
pub struct SectionOrderer<'deck> {
    deck: &'deck LaidOutDeck,
}

impl<'deck> SectionOrderer<'deck> {
    /// Create a new orderer bound to the given deck.
    #[must_use]
    pub fn new(deck: &'deck LaidOutDeck) -> Self {
        Self { deck }
    }

    /// Return all auto-generated sections in kind order (ExecutiveSummary,
    /// then RiskRegister, then any future custom auto-generated sections in
    /// source order).
    ///
    /// Empty sections (no items) are excluded per BC-4.02.002 invariant 2.
    #[must_use]
    pub fn auto_sections(&self) -> Vec<&GeneratedSection> {
        todo!(
            "SectionOrderer::auto_sections — not yet implemented (STORY-042 Step 4). \
             deck.sections len: {}",
            self.deck.sections.len()
        )
    }

    /// Return all manually-authored sections in their declared order
    /// (preserving DSL source order from `LaidOutDeck.sections`).
    ///
    /// Sections with no `register_content` entries (empty manual sections) are
    /// still emitted — the empty-section guard applies only to auto-generated
    /// sections (BC-4.02.002 invariant 2 is scoped to auto sections).
    #[must_use]
    pub fn manual_sections(&self) -> Vec<&GeneratedSection> {
        todo!(
            "SectionOrderer::manual_sections — not yet implemented (STORY-042 Step 4). \
             deck.sections len: {}",
            self.deck.sections.len()
        )
    }

    /// Return sections in the canonical document order:
    /// auto-generated sections first, then manually-authored sections
    /// (BC-4.02.002 postcondition 5, items 3 and 4).
    ///
    /// This is the combined output list that `DocumentBodySerializer` appends
    /// after the per-slide narrative body.
    #[must_use]
    pub fn ordered_sections(&self) -> Vec<&GeneratedSection> {
        todo!(
            "SectionOrderer::ordered_sections — not yet implemented (STORY-042 Step 4). \
             deck.sections len: {}",
            self.deck.sections.len()
        )
    }
}

// Suppress "unused import" on SectionSource until Step 4 when it's needed.
const _: () = {
    let _ = std::mem::size_of::<SectionSource>();
};
