//! Document section ordering for DOCX output.
//!
//! [`SectionOrderer`] implements BC-4.02.002 postcondition 5 — the required
//! document structure ordering:
//!
//! ```text
//! 1. Per-slide narrative body (from STORY-041 / BC-4.02.001)
//! 2. Auto-generated sections (ExecutiveSummary, RiskRegister, …)
//! 3. Manually-authored sections (methodology, scope, appendix, …)
//!    unless a manual section declares an earlier position
//! ```
//!
//! ## Ordering algorithm
//!
//! `SectionOrderer::ordered_sections` returns the `&[GeneratedSection]` slice
//! from `LaidOutDeck.sections` partitioned and sorted by:
//! 1. `SectionSource::AutoGenerated` sections first (in source order), with
//!    empty-items sections excluded (BC-4.02.002 invariant 2).
//! 2. `SectionSource::ManuallyAuthored` sections second (in source order).
//!
//! The narrative body paragraphs (per-slide Heading1 + Normal content) are
//! written by `DocumentBodySerializer` BEFORE `SectionOrderer` output —
//! they are not included in this struct's output.
//!
//! ## BC-4.02.002 invariant 3 — no merging
//!
//! Manual sections are placed at their declared position, NOT merged with
//! auto-generated sections of the same name.

use slideforge_layout::{
    LaidOutDeck,
    sections::{GeneratedSection, SectionSource},
};

/// Orders document sections for `DocumentBodySerializer` consumption.
///
/// Reads `LaidOutDeck.sections` and returns two ordered lists:
/// - `auto_sections()`: auto-generated sections in source order, empty excluded
/// - `manual_sections()`: manually-authored sections in declared order
pub struct SectionOrderer<'deck> {
    /// The laid-out deck whose sections are being ordered.
    deck: &'deck LaidOutDeck,
}

impl<'deck> SectionOrderer<'deck> {
    /// Create a new orderer bound to the given deck.
    #[must_use]
    pub fn new(deck: &'deck LaidOutDeck) -> Self {
        Self { deck }
    }

    /// Return all auto-generated sections in source order.
    ///
    /// Empty sections (no items) are excluded per BC-4.02.002 invariant 2.
    #[must_use]
    pub fn auto_sections(&self) -> Vec<&GeneratedSection> {
        self.deck
            .sections
            .iter()
            .filter(|s| s.source == SectionSource::AutoGenerated && !s.items.is_empty())
            .collect()
    }

    /// Return all manually-authored sections in their declared order
    /// (preserving DSL source order from `LaidOutDeck.sections`).
    ///
    /// Sections with no `register_content` entries (empty manual sections) are
    /// still emitted — the empty-section guard applies only to auto-generated
    /// sections (BC-4.02.002 invariant 2 is scoped to auto sections).
    #[must_use]
    pub fn manual_sections(&self) -> Vec<&GeneratedSection> {
        self.deck
            .sections
            .iter()
            .filter(|s| s.source == SectionSource::ManuallyAuthored)
            .collect()
    }

    /// Return sections in the canonical document order:
    /// auto-generated sections first, then manually-authored sections
    /// (BC-4.02.002 postcondition 5, items 3 and 4).
    ///
    /// This is the combined output list that `DocumentBodySerializer` appends
    /// after the per-slide narrative body.
    #[must_use]
    pub fn ordered_sections(&self) -> Vec<&GeneratedSection> {
        let mut result = self.auto_sections();
        result.extend(self.manual_sections());
        result
    }
}
