//! STORY-042 per-AC demo example — DOCX Auto-Generated Document Sections.
//!
//! Builds a representative [`LaidOutDeck`] containing:
//! - 3 narrative slides (body content)
//! - Auto-generated `executive_summary` section from takeaway fields (AC-001)
//! - Auto-generated `risk_register` section from `severity_cards` data (AC-002)
//! - Manually-authored `methodology` section (AC-003)
//!
//! The deck is exported via [`DocxExporter`].  The binary:
//! 1. Writes the `.docx` to `target/demo_sections_output.docx`
//! 2. Prints a deterministic summary demonstrating each AC
//!
//! # Coverage per acceptance criterion
//!
//! | AC  | Criterion                                        | Demonstrated by                    |
//! |-----|--------------------------------------------------|------------------------------------|
//! | AC-001 | `executive_summary` from takeaway fields      | heading + 2 bullet lines present   |
//! | AC-002 | `risk_register` table from severity_cards     | `<w:tbl>` + 4 row count            |
//! | AC-003 | Manually-authored section at declared position| "Methodology" heading + body text  |
//! | AC-004 | Section ordering: narrative → auto → manual   | byte-offset ordering assertion     |
//! | AC-005 | `risk_register` absent when no severity_cards | second export, Risk Register absent|
//! | AC-006 | `executive_summary` absent when no takeaways  | second export, Exec Summary absent |
//! | AC-007 | Manual section NOT merged with auto           | exactly-one Heading1 count         |
//! | AC-008 | 20 severity_cards → 20-row table              | third export, tr_count == 21       |

use std::io::Read as IoRead;
use std::sync::Arc;

use slideforge_docx::DocxExporter;
use slideforge_layout::{
    sections::{GeneratedSection, OutputFormat, SectionItem, SectionKind, SectionSource},
    types::{BoundingBox, Emu, Frame, FrameContent, LaidOutDeck, LaidOutSlide, PageSize},
};
use slideforge_plugin_api::{ExportOptions, Exporter};
use slideforge_types::{
    Brand, BrandFonts, BrandPalette, Deck, DeckMetadata, InlineNode, OrderedMap, Register,
    RegisteredContent, SourceSpan,
};

// ─── Fixture builders ─────────────────────────────────────────────────────────

/// Build a representative [`Brand`] fixture for demo use.
fn demo_brand() -> Brand {
    Brand {
        name: Arc::from("demo-brand"),
        palette: BrandPalette {
            primary: Arc::from("#003087"),
            secondary: Arc::from("#0066CC"),
            accent: Arc::from("#FF6B35"),
            neutral: Arc::from("#F5F5F5"),
        },
        fonts: BrandFonts {
            heading: Arc::from("Calibri Light"),
            body: Arc::from("Calibri"),
            mono: Arc::from("Courier New"),
        },
        layouts: vec![],
        span: SourceSpan::default(),
    }
}

/// Build an empty [`Deck`] fixture with the given title.
fn demo_deck(title: &str) -> Deck {
    Deck {
        slides: vec![],
        vars: OrderedMap::new(),
        metadata: DeckMetadata {
            title: Some(Arc::from(title)),
            slideforge_version: Arc::from("0.1.0"),
            lang: Some(Arc::from("en-US")),
            author: Some(Arc::from("slideforge demo-recorder")),
            section_order: None,
        },
        registers: OrderedMap::new(),
        section_blocks: vec![],
    }
}

/// Build a minimal single-frame [`LaidOutSlide`] carrying a title and report paragraph.
fn make_slide(index: usize, title: &str, report_text: &str) -> LaidOutSlide {
    LaidOutSlide {
        source_index: index,
        slide_type_keyword: Arc::from("content"),
        frames: vec![Frame {
            bbox: BoundingBox {
                x: Emu(0),
                y: Emu(0),
                width: Emu(9_144_000),
                height: Emu(5_143_500),
            },
            content: FrameContent::Title(Arc::from(title)),
            text_flow: None,
            region_role: None,
        }],
        speaker_notes: Some(Arc::from(format!(
            "NOTES_SENTINEL — slide {index} notes. Should NOT appear in DOCX body."
        ))),
        register_tags: vec![],
        register_content: vec![
            // notes register — must be excluded from DOCX body (BC-4.02.001 invariant 1)
            RegisteredContent {
                register: Register::Notes,
                content: vec![InlineNode::Plain(Arc::from(format!(
                    "NOTES_SENTINEL slide {index}"
                )))],
            },
            // report register — narrative body content
            RegisteredContent {
                register: Register::Report,
                content: vec![InlineNode::Plain(Arc::from(report_text))],
            },
        ],
    }
}

/// Build an auto-generated `executive_summary` [`GeneratedSection`] from takeaway strings.
fn make_executive_summary(takeaways: &[&str]) -> GeneratedSection {
    GeneratedSection {
        kind: SectionKind::ExecutiveSummary,
        source: SectionSource::AutoGenerated,
        items: takeaways
            .iter()
            .map(|t| SectionItem::TakeawayBullet(Arc::from(*t)))
            .collect(),
        heading: Arc::from("Executive Summary"),
        target_formats: vec![OutputFormat::Docx],
        register_content: vec![],
    }
}

/// Build an auto-generated `risk_register` [`GeneratedSection`] from (title, severity, desc) tuples.
fn make_risk_register(rows: &[(&str, &str, &str)]) -> GeneratedSection {
    GeneratedSection {
        kind: SectionKind::RiskRegister,
        source: SectionSource::AutoGenerated,
        items: rows
            .iter()
            .map(|(title, severity, desc)| SectionItem::RiskRow {
                title: Arc::from(*title),
                severity: Arc::from(*severity),
                description: Arc::from(*desc),
                owner: Arc::from("TBD"),
            })
            .collect(),
        heading: Arc::from("Risk Register"),
        target_formats: vec![OutputFormat::Docx],
        register_content: vec![],
    }
}

/// Build a manually-authored [`GeneratedSection`] with a single report-register paragraph.
fn make_manual_section(name: &str, heading: &str, report_text: &str) -> GeneratedSection {
    GeneratedSection {
        kind: SectionKind::ManualSection(Arc::from(name)),
        source: SectionSource::ManuallyAuthored,
        items: vec![],
        heading: Arc::from(heading),
        target_formats: vec![OutputFormat::Docx],
        register_content: vec![RegisteredContent {
            register: Register::Report,
            content: vec![InlineNode::Plain(Arc::from(report_text))],
        }],
    }
}

/// Export a [`Deck`] + [`LaidOutDeck`] pair to raw DOCX bytes using the demo brand.
fn export(deck: &Deck, laid_out: &LaidOutDeck) -> Vec<u8> {
    let brand = demo_brand();
    let opts = ExportOptions::default();
    DocxExporter
        .export(deck, laid_out, &brand, &opts)
        .expect("DocxExporter::export must succeed")
}

/// Read a named entry from a DOCX ZIP archive and return its UTF-8 content.
fn read_zip_member(docx_bytes: &[u8], name: &str) -> String {
    let cursor = std::io::Cursor::new(docx_bytes);
    let mut archive = zip::ZipArchive::new(cursor).expect("valid zip");
    let mut entry = archive
        .by_name(name)
        .unwrap_or_else(|_| panic!("ZIP entry '{name}' not found"));
    let mut buf = String::new();
    entry.read_to_string(&mut buf).expect("UTF-8");
    buf
}

// ─── Main ─────────────────────────────────────────────────────────────────────

#[allow(clippy::too_many_lines)]
fn main() {
    // ═══════════════════════════════════════════════════════════════════════════
    // DECK 1: Full-featured deck — narrative + exec summary + risk register +
    //         manual section
    // ═══════════════════════════════════════════════════════════════════════════

    println!("slideforge STORY-042 — DOCX Auto-Generated Document Sections");
    println!("=============================================================");
    println!();

    let deck = demo_deck("STORY-042 Demo Deck");

    let slides = vec![
        make_slide(0, "Q1 Market Analysis", "Revenue grew 12% year-over-year."),
        make_slide(
            1,
            "Competitive Landscape",
            "Three new entrants identified in Q1.",
        ),
        make_slide(2, "Operational Risks", "Infrastructure capacity at 78%."),
    ];

    let exec_summary = make_executive_summary(&[
        "Key finding: Revenue grew 12% year-over-year.",
        "Key finding: Competitive pressure increasing.",
    ]);

    let risk_register = make_risk_register(&[
        ("R001", "HIGH", "Infrastructure outage risk"),
        ("R002", "MED", "Vendor dependency on single supplier"),
        ("R003", "LOW", "Documentation debt in ops runbooks"),
    ]);

    let methodology = make_manual_section(
        "methodology",
        "Methodology",
        "Analysis used mixed-methods: quantitative financial modelling and qualitative interviews.",
    );

    // Section ordering per BC-4.02.002 postcondition 5:
    // auto-generated sections first (exec summary, risk register), manual last.
    let sections = vec![exec_summary, risk_register, methodology];

    let laid_out = LaidOutDeck {
        page_size: PageSize::default(),
        slides: slides.clone(),
        sections: sections.clone(),
        warnings: vec![],
    };

    let docx_bytes = export(&deck, &laid_out);
    let out_path = std::path::Path::new("target/demo_sections_output.docx");
    std::fs::write(out_path, &docx_bytes).expect("write output file");
    println!("Wrote {} bytes to {}", docx_bytes.len(), out_path.display());
    println!();

    let doc_xml = read_zip_member(&docx_bytes, "word/document.xml");

    // ─── AC-001: executive_summary section from takeaway fields ───────────────
    println!("=== AC-001: Executive Summary from takeaway fields ===");

    let exec_heading_pos = doc_xml
        .find("Executive Summary")
        .expect("AC-001: 'Executive Summary' heading must appear in document.xml");
    println!("  'Executive Summary' heading at offset {exec_heading_pos}");

    assert!(
        doc_xml.contains("Revenue grew 12%"),
        "AC-001: takeaway 'Revenue grew 12%' must appear under Executive Summary"
    );
    assert!(
        doc_xml.contains("Competitive pressure increasing"),
        "AC-001: takeaway 'Competitive pressure increasing' must appear under Executive Summary"
    );
    println!("  Takeaway 1: 'Revenue grew 12%'               PRESENT");
    println!("  Takeaway 2: 'Competitive pressure increasing' PRESENT");
    println!("  PASS");
    println!();

    // ─── AC-002: risk_register table from severity_cards slides ───────────────
    println!("=== AC-002: Risk Register table from severity_cards ===");

    assert!(
        doc_xml.contains("Risk Register"),
        "AC-002: 'Risk Register' heading must appear in document.xml"
    );
    assert!(
        doc_xml.contains("<w:tbl"),
        "AC-002: <w:tbl> must appear for risk register"
    );
    // 1 header row + 3 data rows = 4 total
    let tr_count = doc_xml.matches("<w:tr").count();
    assert_eq!(
        tr_count, 4,
        "AC-002: risk register must have 4 rows (1 header + 3 data); found {tr_count}"
    );
    assert!(
        doc_xml.contains("<w:tblGrid"),
        "AC-002: <w:tblGrid> required (ECMA-376 CT_Tbl minOccurs=1)"
    );
    // Count <w:gridCol: must be exactly 3 (Risk | Severity | Description)
    let gridcol_count = doc_xml.matches("<w:gridCol").count();
    assert_eq!(
        gridcol_count, 3,
        "AC-002: risk register table must have 3 <w:gridCol> entries; found {gridcol_count}"
    );

    println!("  'Risk Register' heading              PRESENT");
    println!("  <w:tbl> element                      PRESENT");
    println!("  <w:tblGrid> + 3 <w:gridCol>          PRESENT (ECMA-376 compliant)");
    println!("  Table rows: 4 (1 header + 3 data)    CORRECT");
    println!("  Header columns: Risk | Severity | Description");
    // Show the table header columns
    let tbl_start = doc_xml.find("<w:tbl").expect("<w:tbl> present");
    let tbl_end = doc_xml
        .find("</w:tbl>")
        .map_or(doc_xml.len(), |p| p + "</w:tbl>".len());
    let tbl_excerpt = &doc_xml[tbl_start..tbl_end.min(tbl_start + 600)];
    // Show header cell text
    let has_risk_col = tbl_excerpt.contains(">Risk</w:t>");
    let has_severity_col = tbl_excerpt.contains(">Severity</w:t>");
    let has_description_col = tbl_excerpt.contains(">Description</w:t>");
    assert!(
        has_risk_col,
        "AC-002: 'Risk' column header must appear in table"
    );
    assert!(
        has_severity_col,
        "AC-002: 'Severity' column header must appear in table"
    );
    assert!(
        has_description_col,
        "AC-002: 'Description' column header must appear in table"
    );
    println!("  Risk/Severity/Description columns    VERIFIED in header row");
    println!("  PASS");
    println!();

    // ─── AC-003: manually-authored section ────────────────────────────────────
    println!("=== AC-003: Manually-authored section at declared position ===");

    assert!(
        doc_xml.contains("Methodology"),
        "AC-003: 'Methodology' heading must appear in document.xml"
    );
    assert!(
        doc_xml.contains("mixed-methods"),
        "AC-003: manual section body text 'mixed-methods' must appear"
    );
    println!("  'Methodology' Heading1               PRESENT");
    println!("  Manual section body text             PRESENT");
    println!("  PASS");
    println!();

    // ─── AC-004: section ordering — narrative → auto → manual ─────────────────
    println!("=== AC-004: Section ordering — narrative → auto-generated → manually-authored ===");

    // Narrative headings: Q1 Market Analysis (first slide)
    let narrative_pos = doc_xml
        .find("Q1 Market Analysis")
        .expect("AC-004: narrative heading 'Q1 Market Analysis' must appear");
    let risk_pos = doc_xml
        .find("Risk Register")
        .expect("AC-004: 'Risk Register' heading must appear");
    let exec_pos = doc_xml
        .find("Executive Summary")
        .expect("AC-004: 'Executive Summary' heading must appear");
    let methodology_pos = doc_xml
        .find("Methodology")
        .expect("AC-004: 'Methodology' heading must appear");

    // Notes must be absent from the DOCX body
    assert!(
        !doc_xml.contains("NOTES_SENTINEL"),
        "AC-004: NOTES_SENTINEL must NOT appear in document.xml (notes register excluded)"
    );

    assert!(
        narrative_pos < exec_pos,
        "AC-004: narrative heading must appear BEFORE Executive Summary; \
         narrative at {narrative_pos}, exec_summary at {exec_pos}"
    );
    assert!(
        exec_pos < risk_pos || risk_pos < methodology_pos,
        "AC-004: auto sections must appear BEFORE manual section"
    );
    assert!(
        narrative_pos < methodology_pos,
        "AC-004: narrative must appear BEFORE manual section; \
         narrative at {narrative_pos}, methodology at {methodology_pos}"
    );

    println!("  Narrative heading ('Q1 Market Analysis') at offset {narrative_pos}");
    println!("  Executive Summary (auto)             at offset {exec_pos}");
    println!("  Risk Register (auto)                 at offset {risk_pos}");
    println!("  Methodology (manual)                 at offset {methodology_pos}");
    println!(
        "  Order: narrative({narrative_pos}) < auto({exec_pos}/{risk_pos}) < manual({methodology_pos})"
    );
    println!("  NOTES_SENTINEL                       ABSENT from document.xml");
    println!("  PASS");
    println!();

    // ─── AC-005 + AC-006: absent-when-empty behavior ──────────────────────────
    println!("=== AC-005 + AC-006: Auto-sections absent when no source data ===");

    // Export a deck with NO sections at all
    let empty_laid_out = LaidOutDeck {
        page_size: PageSize::default(),
        slides: vec![make_slide(
            0,
            "Simple Overview",
            "Only narrative content here.",
        )],
        sections: vec![],
        warnings: vec![],
    };
    let empty_docx = export(&deck, &empty_laid_out);
    let empty_doc_xml = read_zip_member(&empty_docx, "word/document.xml");

    assert!(
        !empty_doc_xml.contains("Risk Register"),
        "AC-005: 'Risk Register' must NOT appear when no severity_cards source data"
    );
    assert!(
        !empty_doc_xml.contains("<w:tbl"),
        "AC-005: no <w:tbl> must appear when no risk register section"
    );
    assert!(
        !empty_doc_xml.contains("Executive Summary"),
        "AC-006: 'Executive Summary' must NOT appear when no takeaway data"
    );

    println!("  No severity_cards: 'Risk Register' absent        PASS (AC-005)");
    println!("  No severity_cards: <w:tbl> absent               PASS (AC-005)");
    println!("  No takeaways: 'Executive Summary' absent         PASS (AC-006)");
    println!();

    // ─── AC-007: manual section NOT merged with auto ──────────────────────────
    println!("=== AC-007: Manual section NOT merged with auto-generated section ===");

    // Use the full deck with all sections — count Heading1 paragraphs for "Methodology"
    let heading1_methodology_count = count_heading1_paragraphs_with_text(&doc_xml, "Methodology");
    assert_eq!(
        heading1_methodology_count, 1,
        "AC-007: exactly one Heading1 paragraph with text 'Methodology' must exist; \
         found {heading1_methodology_count}"
    );
    println!("  Heading1 paragraphs containing 'Methodology': {heading1_methodology_count}");
    println!("  (No auto-methodology rule exists — no spurious duplicate)");
    println!("  PASS");
    println!();

    // ─── AC-008: 20 severity_cards → 20-row table ────────────────────────────
    println!("=== AC-008: 20 severity_cards slides → 20-row risk register table ===");

    let rows_20: Vec<(String, &str, String)> = (0..20)
        .map(|i| {
            let severity = if i % 3 == 0 {
                "HIGH"
            } else if i % 3 == 1 {
                "MED"
            } else {
                "LOW"
            };
            (
                format!("R{i:03}"),
                severity,
                format!("Risk description for item {i}"),
            )
        })
        .collect();
    let row_refs: Vec<(&str, &str, &str)> = rows_20
        .iter()
        .map(|(t, s, d)| (t.as_str(), *s, d.as_str()))
        .collect();

    let risk_20 = make_risk_register(&row_refs);
    let deck_20 = demo_deck("AC-008 20-Row Demo");
    let laid_out_20 = LaidOutDeck {
        page_size: PageSize::default(),
        slides: vec![make_slide(0, "Risk Overview", "20 identified risks.")],
        sections: vec![risk_20],
        warnings: vec![],
    };
    let docx_20 = export(&deck_20, &laid_out_20);
    let xml_20 = read_zip_member(&docx_20, "word/document.xml");

    // Count <w:tr elements: 1 header + 20 data = 21
    let tr_count_20 = xml_20.matches("<w:tr").count();
    assert_eq!(
        tr_count_20, 21,
        "AC-008: risk register must have 21 rows (1 header + 20 data); found {tr_count_20}"
    );
    println!("  20 RiskRow items → <w:tr> count: {tr_count_20} (1 header + 20 data)");
    println!("  PASS");
    println!();

    // ─── Summary ──────────────────────────────────────────────────────────────
    println!("=== SUMMARY ===");
    println!("  AC-001 executive_summary from takeaway fields        PASS");
    println!("  AC-002 risk_register table (1 header + 3 data rows)  PASS");
    println!("  AC-003 manually-authored section at declared position PASS");
    println!("  AC-004 section ordering: narrative → auto → manual   PASS");
    println!("  AC-005 risk_register absent when no severity_cards   PASS");
    println!("  AC-006 executive_summary absent when no takeaways    PASS");
    println!("  AC-007 manual section not merged with auto           PASS");
    println!("  AC-008 20 severity_cards → 21-row table              PASS");
    println!();
    println!("All STORY-042 acceptance criteria PASS.");
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/// Count `<w:p>` paragraphs in `doc_xml` that are:
///   1. Styled as `Heading1` (`w:val="Heading1"` inside the paragraph), AND
///   2. Contain a `<w:t>` run whose content is exactly `target_text`.
fn count_heading1_paragraphs_with_text(doc_xml: &str, target_text: &str) -> usize {
    let para_marker = "<w:p";
    let mut count = 0_usize;
    let mut rest = doc_xml;

    while let Some(start) = rest.find(para_marker) {
        rest = &rest[start + para_marker.len()..];
        let end = rest.find("</w:p>").unwrap_or(rest.len());
        let para_body = &rest[..end];

        let has_heading1 = para_body.contains(r#"w:val="Heading1""#);
        let has_exact_text = para_body.contains(&format!(">{target_text}</w:t>"));

        if has_heading1 && has_exact_text {
            count += 1;
        }

        if end < rest.len() {
            rest = &rest[end + "</w:p>".len()..];
        } else {
            break;
        }
    }

    count
}
