[package]
name = "slideforge-syntax"
description = "Lexer and parser for the slideforge DSL"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"

[dependencies]
slideforge-types = { workspace = true }
chumsky = { workspace = true }
thiserror = { workspace = true }
ordered-float = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
