[package]
name = "slideforge-syntax"
description = "Component crate for slideforge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"

[dependencies]
miette = { workspace = true }
thiserror = { workspace = true }
